pgRouting/pgrouting

tools/test-runner.pl
tools/travis/pgrouting_test.sh

Do not override host, port and user in connection parameters,
unless explicitly specified. This allows usual Postgres rules apply,
e.g., PGHOST, PGPORT and PGUSER environment variables. In particular,
non-network connections could be used now, which is preferred for
automated testing.
Travis test runner script is adapted to changes, too.

Do not override host, port and user in connection parameters for tests

---

CMakeLists.txt

All supported versions of PostgreSQL (9.1+) support and look for
extensions in ${SHARE_DIR}/extension/.

Drop contrib/

---

src/trsp/src/GraphDefinition.cpp

This commit fixes #336 (pgr_trsp on windows returns no route).
I send this pull request also for develop_2_1_0 branch, because after executing `git cherry-pick 8ddc530`,
I encountered some conflict (tab to 4 white spaces .etc).
(See #402 for `master` branch pull request.)

Fixed #336 by initializing GraphDefinition class member variables (for develop_2_1_0 branch)

---

src/trsp/src/GraphDefinition.cpp

This commit fixes #336 (pgr_trsp on windows returns no route).
I send this pull request for `master` branch, because #336 is a bug and it should be fixed also in v2.0.1 release.
To fix the issue on `develop_2_1_0` branch, I think that using `git cherry-pick 8ddc530` will be enough.

Fixed #336 by initializing GraphDefinition class member variables

---

.github/ISSUE_TEMPLATE.md

When you add an issue template to your repository, project contributors will automatically see the template's contents in the issue form body, following https://help.github.com/articles/creating-an-issue-template-for-your-repository/

 Create ISSUE_TEMPLATE.md

---

doc/src/tutorial/custom_query.rst
src/allpairs/src/johnson_driver.cpp
src/common/src/postgres_connection.c
src/dijkstra/src/dijkstraVia_driver.cpp
src/driving_distance/src/boost_interface_drivedist.cpp
src/mainpage.dox
src/withPoints/src/pgr_withPoints.cpp
tools/template/src/function1_driver.cpp

Fix spelling errors reported by the lintian QA tool for the Debian package build.
- missmatch -> mismatch
- requiered -> required
- shoud     -> should
- didnt     -> didn't

Fix spelling errors

---

README.md

Fixes Readme.md online documentation link
http://docs.pgrouting.org/2.2/en/doc/index.html instead of http://docs.pgrouting.org/en/2.2/doc/index.html

correct online documentation link

---

src/vrp_basic/src/VRP_Solver.h

Fixes build failure of pgRouting 2.2.3:
```
src/vrp_basic/src/VRP_Solver.cpp: In member function 'bool CVRPSolver::updateTourCosts(CTourInfo&)':
src/vrp_basic/src/VRP_Solver.cpp:760:59: error: 'ceil' was not declared in this scope
vecStartTimes.push_back(static_cast<int>(ceil(dTravelTime)));
^
```
- Restore `#include <math.h>` that was removed in 2.2.3

Include math.h for ceil() to fix build failure.

---

src/vrp_basic/src/VRP_Solver.h

Some platforms require `stdlib.h` for `rand()` and `srand()` while others include `stdlib.h` implicitly, so always include to be safe.

Include stdlib.h for srand() and rand() to fix build failure

---

src/bd_astar/src/bdastar.h
src/pickDeliver/src/pdp.h
src/vrp_basic/src/VRP.h
src/vrppdtw/src/pdp.h

Fixes #653.
- Fix bogus uses of extern "C" in headers that are meant to be C++ compatible.

Fix bogus uses of extern "C"

---

src/trsp/src/GraphDefinition.cpp
src/trsp/src/trsp.c
src/trsp/src/trsp.h
src/trsp/src/trsp_core.cpp
src/trsp/src/trsp_driver.cpp
src/trsp/src/utils.h

Linting the code for TRSP based on the C and C++ google guidelines.

---

src/ksp/doc/pgr_KSP.rst

Fixes a minor spelling issue in the parameter documentation of ksp.

Fixed spelling in ksp documentation

---

include/c_types/pgr_componentV_t.h
include/c_types/pgr_component_t.h
include/drivers/connectedComponentsV/connectedComponentsV_driver.h
src/connectedComponentsV/src/connectedComponentsV.c
src/connectedComponentsV/src/connectedComponentsV_driver.cpp

Created new structure named pgr_componentV_t

---

src/contraction/src/contractGraph.c

- This commit fixes a petite bug in contractGraph.c file in contraction directory.  
- Replaced `char` in `char *nulls;` with `bool` on line number 188

Fixing petite bug in contractGraph.c

---

doc/queries/doc-pgr_strongComponentsV.queries
src/components/test/doc-pgr_strongComponentsV.result
src/components/test/doc-pgr_strongComponentsV.test.sql
src/components/test/test.conf

Create documentation tests for pgr_strongComponentsV

---

doc/pickDeliver/VRP-category.rst

Fixes typo where `d_service` should be `p_service`

---

doc/src/proposed.rst
include/c_common/get_check_data.h
include/c_common/restrict_input.h
include/c_types/column_info_t.h
src/common/src/CMakeLists.txt
src/common/src/get_check_data.c
src/common/src/restrict_input.c
src/dijkstraTRSP/src/dijkstraTRSP.c
tools/testers/sampledata.sql

Input the data from the restrict table

---

include/c_types/pgr_componentsV_rt.h
include/components/pgr_components.hpp
include/drivers/components/connectedComponentsV_driver.h
include/drivers/components/strongComponentsV_driver.h
src/components/src/connectedComponentsV.c
src/components/src/connectedComponentsV_driver.cpp
src/components/src/strongComponentsV.c
src/components/src/strongComponentsV_driver.cpp

Improve code of connected components and strongly connected components

---

doc/components/CMakeLists.txt
doc/components/components-family.rst
doc/components/pgr_biconnectedComponents.rst
doc/components/pgr_connectedComponentsV.rst
doc/components/pgr_strongComponentsV.rst
doc/src/proposed.rst
doc/src/release_notes.rst

Write documentation for components functions

---

.gitignore
doc/components/CMakeLists.txt
doc/components/components-family.rst
doc/queries/CMakeLists.txt
doc/src/proposed.rst
include/components/pgr_components.hpp
include/components/pgr_componentsGraph.hpp

Improve code and documentation

---

include/components/pgr_components.hpp
include/drivers/components/bridges_driver.h
sql/components/CMakeLists.txt
sql/components/bridges.sql
src/components/src/CMakeLists.txt
src/components/src/articulationPoints_driver.cpp
src/components/src/bridges.c
src/components/src/bridges_driver.cpp

Implement pgr_bridges

---

src/common/src/pgr_assert.cpp

- Replace `__linux__` with `__GLIBC__` for glibc-specific headers and functions.

Fix compiling issues with musl libc

---

README.md
appveyor.yml

I have winnie now running with letsencrypt ssl so better to use the ssl so people don't get not all content on page issecure message sometimes
Fixes # .
-
-
-

Update winnie's badges to use SSL

---

doc/lineGraph/pgr_lineGraphFull.rst
doc/queries/doc-pgr_lineGraphFull.queries
test/lineGraph/doc-pgr_lineGraphFull.result
test/lineGraph/doc-pgr_lineGraphFull.test.sql

This PR contains a fix for the generated queries document for pgr_lineGraphFull, as well as updates to the structure and content of the documentation to make it easier to understand.

Updating documentation for pgr_lineGraphFull

---

include/c_types/pgr_costFlow_t.h
include/costFlow/pgr_minCostMaxFlow.hpp
sql/costFlow/minCostMaxFlow.sql
sql/costFlow/minCostMaxFlow_Cost.sql
src/common/edges_input.c
src/costFlow/minCostMaxFlow.c

Many to many works now.
```reverse_capacity``` DEFAULT ```-1```
```reverse_cost``` DEFAULT ```0```
```
function pgr_mincostmaxflow_cost(text,anyarray,anyarray)
function pgr_mincostmaxflow_cost(text,anyarray,bigint)
function pgr_mincostmaxflow_cost(text,bigint,anyarray)
function pgr_mincostmaxflow_cost(text,bigint,bigint)
function pgr_mincostmaxflow(text,anyarray,anyarray,boolean)
function pgr_mincostmaxflow(text,anyarray,bigint,boolean)
function pgr_mincostmaxflow(text,bigint,anyarray,boolean)
function pgr_mincostmaxflow(text,bigint,bigint,boolean)
```

[WIP] Full implementation of pgr_minCostMaxFlow

---

NEWS
VERSION
doc/bdDijkstra/pgr_bdDijkstra.rst
doc/bdDijkstra/pgr_bdDijkstraCost.rst
doc/dijkstra/pgr_dijkstra.rst
doc/dijkstra/pgr_dijkstraCost.rst
doc/dijkstraTRSP/pgr_dijkstraTRSP.rst
doc/max_flow/flow-family.rst
doc/max_flow/pgr_boykovKolmogorov.rst
doc/max_flow/pgr_edgeDisjointPaths.rst
doc/max_flow/pgr_edmondsKarp.rst
doc/max_flow/pgr_maxCardinalityMatch.rst
doc/max_flow/pgr_maxFlow.rst
doc/max_flow/pgr_pushRelabel.rst
doc/src/pgRouting-concepts.rst
doc/src/proposed.rst
doc/src/release_notes.rst
doc/src/routingFunctions.rst
doc/src/sampledata.rst

This PR makes the flow family of functions official on pgRouting
its on the main page:
https://cvvergara.github.io/pgr/en/index.html
No longer as proposed:
https://cvvergara.github.io/pgr/en/proposed.html
Main page of flow family of functions
https://cvvergara.github.io/pgr/en/flow-family.html
On the functions like [pgr_maxFlow](https://cvvergara.github.io/pgr/en/pgr_maxFlow.html) the *page* button shows: (this is a proposed standard for the page button)
Synopsis
Signature Summary
Parameters
Inner query
Return Columns
See Also
Changes to be committed:
* Updating news about the change
modified:   ../NEWS
modified:   src/release_notes.rst
* Updating the documentation & standarizing it
modified:   max_flow/flow-family.rst
modified:   max_flow/pgr_boykovKolmogorov.rst
modified: …

Flow Family of functions official on pgRouting

---

include/c_types/pgr_kruskal_t.h
include/prim/pgr_kruskal.hpp
sql/prim/kruskal.sql
src/prim/kruskal.c
src/prim/kruskal_driver.cpp

```  
seq | edge| cost| tree_cost
```

C++ implementation of pgr_kruskal

---

NEWS
doc/bdDijkstra/pgr_bdDijkstra.rst
doc/bdDijkstra/pgr_bdDijkstraCost.rst
doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
doc/src/proposed.rst
doc/src/release_notes.rst
doc/src/routingFunctions.rst
sql/bdDijkstra/_bdDijkstra.sql
sql/bdDijkstra/bdDijkstra.sql
sql/bdDijkstra/bdDijkstraCost.sql
sql/costMatrix/bdDijkstraCostMatrix.sql

To view the proposed documentation with this PR: (Note: this links will not be permanent)
[Index](https://cvvergara.github.io/pgr/en/index.html#routing-functions) has the [Bidirectional Dijkstra family](https://cvvergara.github.io/pgr/en/bdDijkstra-family.html) that include:
* [pgr_bdDijkstra](https://cvvergara.github.io/pgr/en/pgr_bdDijkstra.html)
* [pgr_bdDijkstraCost](https://cvvergara.github.io/pgr/en/pgr_bdDijkstraCost.html)
* [pgr_bdDijkstraCostMatrix](https://cvvergara.github.io/pgr/en/pgr_bdDijkstraCostMatrix.html)
--------------
Changes committed:
* Updating NEWS and release notes
modified:   NEWS
modified:   doc/src/release_notes.rst
* Updating availability
modified:   doc/bdDijkstra/pgr_bdDijkstra.rst
modified:   doc/bdDijkstra/pgr_bdDijkstraCost.rst
modified: …

bdDijkstra to official

---

.travis.yml
doc/queries/CMakeLists.txt
doc/queries/doc-pgr_extractVertices.queries
doc/src/index.rst
doc/src/proposed.rst
doc/src/release_notes.back.rst
doc/topology/CMakeLists.txt
doc/topology/pgr_extractVertices.rst
doc/topology/topology-functions.rst
pgtap/topology/extractVertices/edge-cases.sql
pgtap/topology/extractVertices/innerQuery.sql
pgtap/topology/extractVertices/no_crash_test.sql
pgtap/topology/extractVertices/types-check.sql
sql/topology/CMakeLists.txt
sql/topology/extractVertices.sql
test/topology/doc-pgr_extractVertices.result
test/topology/doc-pgr_extractVertices.test.sql
test/topology/test.conf

While fixing pgr_createVerticesTable
I came up with the idea that the user must be the one controlling the table creation.
So extract vertices, does basically the same stuff, but without so much checking that had to go on for safety reasons because of the table creation.
This function needs the source and target columns of an edge table, optionally also the geometry
It also based on an inner query.

Extract vertices

---

cmake/FindPostgreSQL.cmake

Small adjustments to FindPostgreSQL.cmake, needed if installation is performed based on instructions here: https://www.postgresql.org/download/linux/redhat/
Fixes # .
- added to FindPostgreSQL.cmake the custom path of an installation performed following PostgreSQL instructions

Small adjustments to FindPostgreSQL.cmake

---

cmake/FindPostgreSQL.cmake

Fixes #1157.
- Prefer the path given by `pg_config` when searching for POSTGRESQL_EXECUTABLE by changing the [search order](https://cmake.org/cmake/help/v3.0/command/find_program.html) to avoid matching an unrelated executable
This PR is the minimal required change to the logic to fix building on Mac in several typical constellations. I would however rather prefer the following bigger change:
- remove all the 'guesses' of fixed-paths and environment variables
- exclusively rely on the output of `pg_config`, find that according to PATH, overridable by `POSTGRESQL_BIN`
Reason:
- we already are depending on a working `pg_config`, otherwise `POSTGRESQL_LIBRARIES` and `POSTGRESQL_VERSION_STRING` could not be set, and `POSTGRESQL_FOUND` …

Improve FindPostgreSQL.cmake

---

doc/dijkstra/pgr_dijkstra.rst
doc/topology/pgr_extractVertices.rst

This PR fixes the typo `bellow` to `below` in `pgr_dijkstra.rst` and `pgr_extractVertices.rst`.

[doc] Typo corrections

---

pgtap/common/hasnt_v2_signatures.sql
sql/alpha_shape/alpha_shape.sql

Fixes #1192 .
- Replace single quotes in the query passed to `pgr_pointsAsPolygon()` with escaped quotes, stopping a failure if a string comparison is specified in its `WHERE` clause in the subsequent call to `pgr_alphaShape()`

fixed pgr_pointsAsPolygon breaking when comparing strings in WHERE clause

---

doc/src/pgRouting-concepts.rst

Fixes # .
- Fix a wrong apostrophe in pgr_dijkstra select in doc

fix a wrong select apostrophe in doc

---

sql/trsp/trsp_V2.2.sql

Fixes #.
- I have faced the issue with SQL queries for a string to array conversion for integer values. I have updated this setting in my local server and its working fine. decided to push and make a pull request for this.
-
-

implicit cast for via_path integer to text

---

include/tsp/pgr_tsp.hpp

Fixes an assertion problem on TSP
```
ERROR:  AssertFailedException: n > 2 at /home/vicky/pgRouting/pgrouting/include/tsp/pgr_tsp.hpp:572
*** Execution path***
[bt]/usr/lib/postgresql/10/lib/libpgrouting-3.0.so(_Z13get_backtraceB5cxx11v+0x40) [0x7f4acea4712c]
[bt]/usr/lib/postgresql/10/lib/libpgrouting-3.0.so(_ZN9pgrouting3tsp3TSPINS0_7DmatrixEE9annealingEdddlllbd+0x1a4) [0x7f4aceb05bd0]
[bt]/usr/lib/postgresql/10/lib/libpgrouting-3.0.so(do_pgr_tsp+0x521) [0x7f4aceb035d0]
[bt]/usr/lib/postgresql/10/lib/libpgrouting-3.0.so(+0x5f992b) [0x7f4aceb0292b]
```

fix edge case for tsp when there is one or two nodes

---

doc/bdAstar/pgr_bdAstarCost.rst

**Using Defaults**: Example: From vertex 2 to vertex 3 on a directed graph.
**one-to-one**: Example: From vertex 2 to vertex 3 on an directed graph using heuristic 2
**one-to-many**: Example: From vertex 2 to vertices {3,11} on a directed graph using heuristic 3 and factor=3.5
**many-to-one**: Example: From vertices {7, 2} to vertex 3 on a undirected graph using heuristic 4
**many-to-many**: Example: From vertices {7, 2} to vertices {3,11} on a directed using default heuristic 5 and factor=0.5

[doc] pgr_bdAstarCost fixing #1329

---

tools/developer/taptest.sh

Back porting fix of #1364 to 3.0 (in master 3.0.1)

test database name fixed

---

.travis.yml

When transifex does a PR it does not affect code so this prevents Travis code checking and only allows it to check documentation.
when part of the commit msg has: "translation completed for the source file"
it only checks documentations
This PR is testing the feature here: https://travis-ci.com/github/cvvergara/pgrouting/builds/174856317
Where the test done on all jobs is done only to documentation

[travis] skiping code check 

---

.github/workflows/check-files.yml

Signature files for the same minor should remain the same
The test fails when that is not the case

[actions] test for signature files not changing on same minor

---

doc/conf.py.in

- Removed the generated links from `linkcheck_ignore`

Removed the generated links from linkcheck_ignore

---

doc/coloring/coloring-family.rst
doc/coloring/pgr_sequentialVertexColoring.rst

- Defined the parameters and the result columns in the coloring family doc, instead of the sequentialVertexColoring doc.
- Referenced these parameters in the sequentialVertexColoring doc.

Fixed coloring family and sequentialVertexColoring documentation

---

doc/conf.py.in

- Removed the links from linkcheck_ignore

GSoC 2020 Removed links from linkcheck_ignore

---

doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
locale/en/LC_MESSAGES/pgr_binaryBreadthFirstSearch.po
locale/pot/pgr_binaryBreadthFirstSearch.pot

On experimental pgr_binaryBreadthFirstSearch there is a link to
https://codeforces.com/blog/entry/22276
Which is a site of:
"Codeforces is a website that hosts competitive programming contests."
- Reference to a contest for an algorithm is not a reliable source
- Its so unreliable that it is out of service and its blocking #1621 PR

Removing codeforce link

---

doc/src/pgRouting-concepts.rst

his is wrong:
Identifier of the starting vertex. Used when multiple starting vetrices are in the query.
Should be
Identifier of the starting vertex.

Fixing description of cost matrix

---

NEWS
doc/src/release_notes.rst
include/contraction/pgr_contractionGraph.hpp
pgtap/contraction/linear/directed/issue-1647.sql
pgtap/contraction/linear/undirected/issue-1647.sql

Backporting fix on 3.0 of 1647
`pgr_contraction` is an official function so backporting to 3.0 is needed
- The fix
- The the release notes about the backporting

Issue 1647 3.0

---

NEWS
doc/src/release_notes.rst
include/contraction/pgr_contractionGraph.hpp
pgtap/contraction/linear/directed/issue-1647.sql
pgtap/contraction/linear/undirected/issue-1647.sql

fix on 3.1 of #1647 
`pgr_contraction` is an official function so backporting to 3.0 is needed in #1719 
- The fix
- The the release notes about the backporting and the fix on 3.1.1

Issue 1647 3.1

---

include/chinese/pgr_chinesePostman.hpp
include/max_flow/pgr_minCostMaxFlow.hpp

Backporting fixes for reopened #1300  .

[chinese] fixing server crash on 3.0

---

NEWS
doc/src/release_notes.rst
docqueries/version/doc-full_version.result
pgtap/tsp/issues/issue-1760.sql
src/cpp_common/Dmatrix.cpp
src/tsp/euclideanDmatrix.cpp

Backport from #1768  to 3.0 from fixes on PR #1760
Reminder: Do Squash Merge

Fix Issue 1760 on 3.0

---

doc/conf.py.in

- Added broken link to `linkcheck_ignore`

Added broken link to linkcheck_ignore on 3.0

---

.github/workflows/check-files.yml
CMakeLists.txt
NEWS
doc/src/release_notes.rst
docqueries/version/doc-full_version.result
docqueries/version/doc-version.result

- Modifying action to verify that NEWS section has the corresponding version
- Pumping up from 3.0.4 to 3.0.5

Pumpup to 3.0.5

---

.github/workflows/check-files.yml
CMakeLists.txt
NEWS
doc/src/release_notes.rst
docqueries/version/doc-full_version.result
docqueries/version/doc-version.result

- Action to verify section in news exists for new version
- Porting documentation section from 3.0.5
- pumping up to 3.1.3

Pumpup to 3.1.3

---

.github/workflows/check-files.yml
CMakeLists.txt
NEWS
doc/src/release_notes.rst

* Action to verify section in news exists for new version
* Porting documentation section from 3.0.5
* Porting documentation section from 3.1.2

Porting pumpups

---

.github/workflows/macos.yml

- Add CI scripts for macOS Environment
I've written GH Actions for macOS environment. This pull request makes us build and test pgRouting on macOS.
NOTE: At first, I've tried to test multiple PostgreSQL versions with version matrix but I've given up it, since only latest version doesn't have version suffix on the homebrew package name like `postgresql@13`.

Support macOS on CI

---

README.md
doc/src/pgRouting-introduction.rst

Fixes #1851
- Changed license to GPL-2.0+

Change license to GPL-2.0+ on 3.1

---

CONTRIBUTING.md
README.md
doc/src/pgRouting-introduction.rst

Fixes #1851.
- Ports #1858 to 3.0

Change license to GPL-2.0-or-later on 3.0

---

CONTRIBUTING.md
README.md
doc/src/pgRouting-introduction.rst

Fixes #1851.
- Changed license to GNU General Public License v2.0 or later.
- See https://github.com/pgRouting/pgrouting/pull/1852#issuecomment-765063536

Change license to GPL-2.0-or-later on 3.1

---

.github/workflows/release.yml
NEWS
doc/src/release_notes.rst
requirements.txt
tools/release-scripts/notes2news.pl

- Ports #1857 to 3.2
- Fixed NEWS and release_notes (changed `#1825` to `#1850`)

Add GitHub Actions script for releases on 3.2

---

.github/workflows/release.yml
NEWS
doc/src/release_notes.rst
requirements.txt
tools/release-scripts/notes2news.pl

- Adds script for automating releases and publishing documentation.
- Fixes `notes2news.pl` to generate `NEWS` in proper markdown format.
- Modifies `release_notes` and `NEWS`, so that NEWS is in proper markdown.
- Upgrade Sphinx and sphinx-bootstrap-theme version in `requirements.txt`, for documentation generation.

Add GitHub Actions script for releases on 3.1

---

doc/src/pgRouting-concepts.rst

The documentation was describing osm2pgrouting, shp2pgsql, ogr2ogr, osm2pgsql as equivalent tools. The reality is that osm2pgrouting is preferred (and officially supported), whereas the other three require additional steps, some of them not documented. This change fixes that.
There are some other minor changes to help new users understand the steps to get their pgRouting set up and first path calculated.
- osm2pgrouting described as the preferred tool
- assorted minor changes

osm2pgrouting as the preferred way to load data

---

.github/workflows/documentation.yml
.github/workflows/publish-users-doc.yml

- Modified `documentation.yml` file to also run on pull requests, specifically for translations.
- Added script to publish users documentation on `master` & `develop`
- On push, when any file changes on the `doc/`, `docqueries/`, or `locale/` directory, or
- Manually from GitHub actions, if required.

Add GitHub actions script for publishing documentation

---

.github/workflows/publish-users-doc.yml
.github/workflows/release.yml
CONTRIBUTING.md
README.md
tools/NOTES.txt

- Ports typo fixes (#1870, #1839, #1837) to 3.2
- Added commit hash in the message during publishing documentation. (Refer https://github.com/pgRouting/pgrouting/pull/1878#issuecomment-798831665)

Port typo fixes to 3.2, add commit hash while publishing doc

---

.github/workflows/documentation.yml
.github/workflows/publish-users-doc.yml
.github/workflows/release.yml

- Ports #1877 to 3.1
- Added commit hash in the message during publishing documentation.

Add GitHub actions script for publishing documentation to 3.1

---

include/c_types/contracted_rt.h
include/drivers/contraction/contractGraph_driver.h
src/contraction/contractGraph_driver.cpp

Fixes #1895 .
- changes to contracted_rt.h
- adjusting code based on changes on contracted_rt.h

fix for Issue1895 contracted_rt

---

include/c_common/coordinates_input.h
include/c_types/coordinate_t.h
src/common/coordinates_input.c

Fixes #1896 .
- changes to coordinate_t.h
- adjusting code based on changes on structure Coordinate_t

fix for Issue1896 Coordinate_t

---

include/c_types/line_graph_full_rt.h
include/drivers/lineGraph/lineGraphFull_driver.h
src/lineGraph/lineGraphFull.c
src/lineGraph/lineGraphFull_driver.cpp

Fixes #1901  .
- changes to line_graph_full_rt.h
- adjusting code based on changes on structure Line_graph_full_rt

fix for Issue1901 Line_graph_full_rt

---

include/c_types/pickDeliver/schedule_rt.h
include/drivers/pickDeliver/pickDeliverEuclidean_driver.h
include/drivers/pickDeliver/pickDeliver_driver.h
include/vrp/pgr_pickDeliver.h
include/vrp/solution.h
include/vrp/vehicle.h
src/pickDeliver/pgr_pickDeliver.cpp
src/pickDeliver/pickDeliver.c
src/pickDeliver/pickDeliverEuclidean.c
src/pickDeliver/pickDeliverEuclidean_driver.cpp
src/pickDeliver/pickDeliver_driver.cpp
src/pickDeliver/solution.cpp
src/pickDeliver/vehicle.cpp

Fixes #1922  .
- more meaningful name to the struct: General_vehicle_orders_t -> Schedule_rt
- and the required simplification

Making compilation faster general vehicle orders t

---

include/drivers/allpairs/floydWarshall_driver.h
include/drivers/allpairs/johnson_driver.h

Fixes #2051.
- Changes made to headers in `include/drivers/allpairs`.

Adjust drivers in allpairs

---

include/drivers/astar/astar_driver.h

Fixes #2054.
- Changes made to headers in `include/drivers/astar`.

Adjust drivers in astar

---

include/drivers/bdAstar/bdAstar_driver.h
src/bdAstar/bdAstar.c

Fixes #2056
- Changes made to headers in `include/drivers/bdAstar`.

Adjust drivers in bdAstar

---

include/drivers/bdDijkstra/bdDijkstra_driver.h

Fixes # 2063
- Changes made to headers in `include/drivers/bdDijkstra`.

Adjust drivers in bdDijkstra

---

include/drivers/bellman_ford/bellman_ford_driver.h
include/drivers/bellman_ford/bellman_ford_neg_driver.h
include/drivers/bellman_ford/edwardMoore_driver.h

Fixes #2065
- Changes made to headers in `include/drivers/bellman_ford`.

Adjust drivers in bellman_ford

---

include/drivers/chinese/chinesePostman_driver.h

Fixes #2069  
- Changes made to headers in `include/drivers/chinese`.

Adjust drivers in chinese

---

include/drivers/breadthFirstSearch/binaryBreadthFirstSearch_driver.h
include/drivers/breadthFirstSearch/breadthFirstSearch_driver.h

Fixes #2067 
- Changes made to headers in `include/drivers/breadthFirstSearch`.

Adjust drivers in breadthFirstSearch

---

include/drivers/components/articulationPoints_driver.h
include/drivers/components/biconnectedComponents_driver.h
include/drivers/components/bridges_driver.h
include/drivers/components/connectedComponents_driver.h
include/drivers/components/makeConnected_driver.h
include/drivers/components/strongComponents_driver.h

Fixes #2073  
- Changes made to headers in `include/drivers/components`.
- Remove unnecessary struct and includes, added includes for int64_t.

Adjust drivers in components

---

include/drivers/contraction/contractGraph_driver.h

Fixes #2075 
- Changes made to headers in `include/drivers/contraction`.

Adjust drivers in contraction

---

include/drivers/dagShortestPath/dagShortestPath_driver.h

Fixes #2077 
- Changes made to headers in `include/drivers/dagShortestPath`.

Adjust drivers in dagShortestPath

---

include/drivers/dijkstra/dijkstraVia_driver.h
include/drivers/dijkstra/dijkstra_driver.h

Fixes #2079 
- Changes made to headers in `include/drivers/dijkstra`.

Adjust drivers in dijkstra

---

include/drivers/dominator/lengauerTarjanDominatorTree_driver.h

Fixes #2081 
- Changes made to headers in `include/drivers/dominator`.

Adjust drivers in dominator

---

include/drivers/max_flow/edge_disjoint_paths_driver.h
include/drivers/max_flow/max_flow_driver.h
include/drivers/max_flow/minCostMaxFlow_driver.h

Fixes #2091 
- keyword using instead of typedef in C++ to avoid the creation of a new type/type-id.
- Fixed the files edge_disjoint_paths_driver, max_flow_driver and minCostMaxFlow_driver.

Adjust drivers: max_flow

---

include/drivers/topologicalSort/topologicalSort_driver.h

Fixes #2104 
-keyword `using` instead of `typedef` in C++ to avoid the creation of a new type/type-id.
-Changes made to header in `include/drivers/topologicalSort`.

Adjust drivers: topologicalSort

---

include/drivers/yen/ksp_driver.h
include/drivers/yen/turnRestrictedPath_driver.h
include/drivers/yen/withPoints_ksp_driver.h

Fixes #2106  .
- Changes made to headers in `include/drivers/yen`.

Adjust drivers: yen

---

.github/workflows/locale-and-website.yml
doc/CMakeLists.txt
tools/transifex/remove_obsolete_entries.sh

- Add code to automatically update locale on `develop`, when PR is merged to `develop`.
- Add script to remove the obsolete entries, i.e. lines starting with `#~` from .po files
- Tested on my fork: [develop branch](https://github.com/krashish8/pgrouting/commits/develop), [Actions Workflow](https://github.com/krashish8/pgrouting/actions/workflows/locale-and-website.yml)

Add automatic locale update in GitHub actions

---

.github/workflows/locale-and-website.yml

- Add code to automatically run locale and documentation actions only on the pgRouting's repository (not on forks)
- Should run when a PR is merged to either main/develop branch on the pgRouting's repository.
- Tested on forks: https://github.com/krashish8/pgrouting/actions/runs/1285246433 (The workflow run was skipped)

Run locale & doc actions only on the main repository

---

include/drivers/mincut/stoerWagner_driver.h

Fixes #2111.
- Keyword `using` instead of `typedef` in C++
- Changes made to header in include/drivers/mincut

[mincut] Adjust drivers

---

include/drivers/traversal/depthFirstSearch_driver.h

Fixes #2116 
- Used using keyword for C++ and typedef otherwise

[traversal] adjusting drivers

---

NEWS
doc/src/experimental.rst
doc/src/proposed.rst
doc/src/release_notes.rst
doc/traversal/pgr_depthFirstSearch.rst
doc/traversal/traversal-family.rst
sql/traversal/depthFirstSearch.sql

Fixes #2201
-   SQL files comments marked as proposed
-   Documentation files Experimental -> proposed
-   Updated NEWS and release notes

[depthFirstSearch] promote to proposed

---

include/drivers/coloring/edgeColoring_driver.h
pgtap/coloring/edgeColoring/edge-cases.sql

- Fixing *include/drivers/coloring/edgeColoring_driver.h* https://github.com/pgRouting/pgrouting/blob/main/include/drivers/coloring/edgeColoring_driver.h#L2
- Fixing *pgtap/coloring/edgeColoring/edge-cases.sql* https://github.com/veenits123/pgrouting/issues/1

[pgr_edgeColoring] Fixing some bugs

---

docqueries/bdAstar/doc-pgr_bdAstarCostMatrix.result
docqueries/bdAstar/doc-pgr_bdAstarCostMatrix.test.sql
docqueries/bdDijkstra/doc-pgr_bdDijkstraCostMatrix.result
docqueries/bdDijkstra/doc-pgr_bdDijkstraCostMatrix.test.sql
docqueries/dijkstra/doc-pgr_dijkstraCostMatrix.result
docqueries/dijkstra/doc-pgr_dijkstraCostMatrix.test.sql
docqueries/tsp/doc-pgr_TSP.result
docqueries/tsp/doc-pgr_TSP.test.sql
docqueries/withPoints/doc-pgr_withPointsCostMatrix.result
docqueries/withPoints/doc-pgr_withPointsCostMatrix.test.sql

* removing `randomize` parameter from calls

[docqueries][tsp] removing randomize parameter from calls (#2234)

---

doc/dijkstra/pgr_dijkstraVia.rst
doc/src/pgRouting-concepts.rst

No issue opened.
As a prelude of #2244 
* the `|` helps showing the title reached when clicking on an internal link
* Using `.. list-table::` to avoid wrapping on type column
* wrapping 
* non wrapping
* It also facilitates the writting of long descriptions
* using double backquote to indicate things that not to be translated (like column names, or postgres types)
* using bold when things can be translated like **ANY-INTEGER**
* organizing it a little better

Change table style

---

doc/allpairs/allpairs-family.rst
doc/allpairs/pgr_floydWarshall.rst
doc/allpairs/pgr_johnson.rst
doc/alpha_shape/pgr_alphaShape.rst
doc/dijkstra/dijkstra-family.rst
doc/dijkstra/pgr_dijkstra.rst
doc/dijkstra/pgr_dijkstraCost.rst
doc/src/pgRouting-concepts.rst
docqueries/dijkstra/doc-pgr_dijkstra.result
docqueries/dijkstra/doc-pgr_dijkstra.test.sql

Fixes #2244  .
Commit names are directory based.
Marking as done on initial issue so no one else takes the directory files.
Besides of using `parse-literal` the following was made
- allpairs
- Cleaned documentation
- Added information to the family

Using parse-literal on allpairs, alphashape & pgr_dijkstra

---

doc/dijkstra/dijkstra-family.rst
doc/dijkstra/pgr_dijkstra.rst
doc/dijkstra/pgr_dijkstraCost.rst
doc/dijkstra/pgr_dijkstraCostMatrix.rst
doc/dijkstra/pgr_dijkstraNear.rst
doc/dijkstra/pgr_dijkstraNearCost.rst
doc/dijkstra/pgr_dijkstraVia.rst
doc/src/costMatrix-category.rst
doc/src/pgRouting-concepts.rst
doc/src/via-category.rst
doc/trsp/pgr_trspVia.rst
docqueries/dijkstra/doc-pgr_dijkstraCost.result
docqueries/dijkstra/doc-pgr_dijkstraCost.test.sql
docqueries/dijkstra/doc-pgr_dijkstraCostMatrix.result
docqueries/dijkstra/doc-pgr_dijkstraCostMatrix.test.sql
docqueries/dijkstra/doc-pgr_dijkstraNear.result
docqueries/dijkstra/doc-pgr_dijkstraNear.test.sql
docqueries/dijkstra/doc-pgr_dijkstraNearCost.test.sql
docqueries/dijkstra/doc-pgr_dijkstraVia.result
docqueries/dijkstra/doc-pgr_dijkstraVia.test.sql

Fixes #2244  .
- pgr_dijkstraCost
- pgr_dijkstraCostMatrix
- pgr_dijkstraVia
- pgr_dijkstraNear
- pgr_dijkstraNearCost

Dijkstra parsed literal

---

doc/dijkstra/pgr_dijkstraVia.rst
doc/src/costMatrix-category.rst
doc/src/pgRouting-concepts.rst
doc/src/via-category.rst
doc/src/withPoints-category.rst
doc/trsp/pgr_trspVia.rst
doc/trsp/pgr_trspVia_withPoints.rst
doc/withPoints/pgr_withPoints.rst
doc/withPoints/pgr_withPointsCost.rst
doc/withPoints/pgr_withPointsCostMatrix.rst
doc/withPoints/pgr_withPointsVia.rst
doc/withPoints/withPoints-family.rst
docqueries/withPoints/doc-pgr_withPoints.result
docqueries/withPoints/doc-pgr_withPoints.test.sql
docqueries/withPoints/doc-pgr_withPointsCost.result
docqueries/withPoints/doc-pgr_withPointsCost.test.sql
docqueries/withPoints/doc-pgr_withPointsCostMatrix.result
docqueries/withPoints/doc-pgr_withPointsCostMatrix.test.sql

Fixes #2244 .
Using parsed literal and there is also refinement of the documentation.
- pgr_withPoints
- pgr_withPointsCost
- pgr_withPointsCostMatrix
- pgr_withPointsVia
- via-category
More refinement (for consistency) will be needed after all the withPoints family of functions are finished.

With points using parsed literal

---

NEWS
doc/src/release_notes.rst
include/coloring/pgr_bipartite_driver.hpp
include/coloring/pgr_sequentialVertexColoring.hpp
include/components/pgr_makeConnected.hpp
include/dominator/pgr_lengauerTarjanDominatorTree_driver.hpp
src/bdAstar/bdAstar_driver.cpp
src/bdDijkstra/bdDijkstra_driver.cpp
src/coloring/pgr_edgeColoring.cpp
src/components/componentsResult.cpp
src/trsp/pgr_trspHandler.cpp

Fixes #2216 .
- Modified src code to eliminate warnings

Warning clang fix dev

---

.github/workflows/update.yml
.github/workflows/windows.yml
CMakeLists.txt
NEWS
doc/conf.py.in
doc/src/release_notes.rst
docqueries/version/doc-full_version.result
docqueries/version/doc-version.result
include/cpp_common/basePath_SSEC.hpp
include/trsp/pgr_trspHandler.h
pgtap/coloring/edgeColoring/edge-cases.sql
src/common/basePath_SSEC.cpp
src/trsp/new_trsp.c
src/trsp/pgr_trspHandler.cpp
src/trsp/trsp_driver.cpp
src/version/CPPLINT.cfg
tools/testers/pg_prove_tests.sh

Fixes #2266  .
- Fix an issue with reading restrictions on TRSP
- Pumps up to 3.3.1
- Adjusts windows action to changes on action
- Ignores a link not available at this point in time

Fix trsp bug main

---

doc/coloring/coloring-family.rst
doc/coloring/pgr_bipartite.rst
doc/coloring/pgr_edgeColoring.rst
doc/coloring/pgr_sequentialVertexColoring.rst
doc/conf.py.in
doc/driving_distance/drivingDistance-category.rst
doc/spanningTree/kruskal-family.rst
doc/spanningTree/pgr_kruskal.rst
doc/spanningTree/pgr_kruskalBFS.rst
doc/spanningTree/pgr_kruskalDD.rst
doc/spanningTree/pgr_kruskalDFS.rst
doc/spanningTree/pgr_prim.rst
doc/spanningTree/pgr_primBFS.rst
doc/spanningTree/pgr_primDD.rst
doc/spanningTree/pgr_primDFS.rst
doc/spanningTree/prim-family.rst
doc/spanningTree/spanningTree-family.rst
doc/src/pgRouting-concepts.rst
doc/src/routingFunctions.rst
doc/traversal/BFS-category.rst
doc/traversal/CMakeLists.txt
doc/traversal/DFS-category.rst
doc/traversal/pgr_depthFirstSearch.rst
doc/traversal/traversal-family.rst
docqueries/traversal/doc-pgr_depthFirstSearch.result
docqueries/traversal/doc-pgr_depthFirstSearch.test.sql

Fixes #2244 
Using parsed literal and refining documentation:
- doc/spanningTree/spanningTree-family.rst
- doc/spanningTree/prim-family.rst
-  doc/spanningTree/kruskal-family.rst
- doc/spanningTree/pgr_kruskal.rst
- doc/spanningTree/pgr_kruskalBFS.rst
- doc/spanningTree/pgr_kruskalDD.rst
- doc/spanningTree/pgr_kruskalDFS.rst
- doc/spanningTree/pgr_prim.rst
- doc/spanningTree/pgr_primBFS.rst
- doc/spanningTree/pgr_primDD.rst
- doc/spanningTree/pgr_primDFS.rst
- doc/traversal/traversal-family.rst
- doc/traversal/pgr_depthFirstSearch.rst
Creating 2 new categories under traversal:
- DFS-category
- BFS-category

Spanntree parsed literal

---

doc/bdDijkstra/bdDijkstra-family.rst
doc/bdDijkstra/pgr_bdDijkstra.rst
doc/bdDijkstra/pgr_bdDijkstraCost.rst
doc/bdDijkstra/pgr_bdDijkstraCostMatrix.rst
doc/dijkstra/dijkstra-family.rst
doc/dijkstra/pgr_dijkstra.rst
doc/dijkstra/pgr_dijkstraCost.rst
doc/dijkstra/pgr_dijkstraCostMatrix.rst
doc/max_flow/pgr_edgeDisjointPaths.rst
doc/src/cost-category.rst
doc/src/costMatrix-category.rst
docqueries/bdDijkstra/doc-pgr_bdDijkstra.result
docqueries/bdDijkstra/doc-pgr_bdDijkstra.test.sql
docqueries/bdDijkstra/doc-pgr_bdDijkstraCost.result
docqueries/bdDijkstra/doc-pgr_bdDijkstraCost.test.sql
docqueries/bdDijkstra/doc-pgr_bdDijkstraCostMatrix.result
docqueries/bdDijkstra/doc-pgr_bdDijkstraCostMatrix.test.sql
docqueries/dijkstra/doc-pgr_dijkstra.result
docqueries/dijkstra/doc-pgr_dijkstra.test.sql
docqueries/dijkstra/doc-pgr_dijkstraCost.result
docqueries/dijkstra/doc-pgr_dijkstraCost.test.sql
docqueries/dijkstra/doc-pgr_dijkstraCostMatrix.result
docqueries/dijkstra/doc-pgr_dijkstraCostMatrix.test.sql

Fixes #2244  .
Using parsed literal on the following functions
- pgr_bdDijkstra
- pgr_bdDijkstraCost
- pgr_bdDijkstraCostMatrix
Also refined some categories and families involved

Bd dijkstra parsed literal

---

doc/topology/pgr_createTopology.rst
doc/topology/pgr_extractVertices.rst

Highlights the use of `pgr_extractVertices` to create a topology.
See:  #2255 

[extractVertices] refining documentation

---

.github/workflows/boost_version.yml
.github/workflows/check-files.yml
.github/workflows/check-queries.yml
.github/workflows/clang.yml
.github/workflows/doc-check.yml
.github/workflows/locale-and-website.yml
.github/workflows/macos.yml
.github/workflows/release.yml
.github/workflows/ubuntu.yml
.github/workflows/update.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

doc/dijkstra/pgr_dijkstra.rst
docqueries/dijkstra/doc-pgr_dijkstra.result
docqueries/dijkstra/doc-pgr_dijkstra.test.sql

Fixes mistake on #2273.
- change of pgr_bddijkstra to pgr_dijkstra on pgr_dijkstra.test.sql

pgr_bddijkstra to pgr_dijkstra

---

locale/es/LC_MESSAGES/migration.po
locale/zh_Hans/LC_MESSAGES/migration.po

Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [pgRouting/index](https://weblate.osgeo.org/projects/pgrouting/index/).
It also includes following components:
* [pgRouting/pgr_nodeNetwork](https://weblate.osgeo.org/projects/pgrouting/pgr_nodenetwork/)
* [pgRouting/pgRouting-concepts](https://weblate.osgeo.org/projects/pgrouting/pgrouting-concepts/)
* [pgRouting/pgr_johnson](https://weblate.osgeo.org/projects/pgrouting/pgr_johnson/)
* [pgRouting/allpairs-family](https://weblate.osgeo.org/projects/pgrouting/allpairs-family/)
* [pgRouting/pgr_maxCardinalityMatch](https://weblate.osgeo.org/projects/pgrouting/pgr_maxcardinalitymatch/)
* [pgRouting/BFS-category](https://weblate.osgeo.org/projects/pgrouting/bfs-category/)
* …

Translations update from OSGeo Weblate

---

NEWS
doc/src/release_notes.rst
include/yen/pgr_ksp.hpp
pgtap/ksp/ksp/edge_cases/issue_1891.pg

Fixes #1891 
* fix issue
* tap test about expected results
* notification on NEWS

Fix issue ksp 1891

---

doc/circuits/pgr_hawickCircuits.rst
doc/conf.py.in
doc/ordering/pgr_cuthillMckeeOrdering.rst
doc/pickDeliver/pgr_pickDeliver.rst
doc/pickDeliver/pgr_pickDeliverEuclidean.rst
doc/src/pgRouting-concepts.rst
doc/topology/pgr_analyzeGraph.rst
doc/topology/pgr_analyzeOneWay.rst
doc/topology/pgr_createTopology.rst
doc/topology/pgr_createVerticesTable.rst
doc/topology/pgr_degree.rst
doc/topology/pgr_extractVertices.rst
doc/topology/pgr_nodeNetwork.rst
doc/trsp/pgr_trsp.rst
doc/trsp/pgr_trspVia.rst
doc/trsp/pgr_trspVia_withPoints.rst
doc/trsp/pgr_trsp_withPoints.rst
doc/trsp/pgr_turnRestrictedPath.rst
doc/utilities/pgr_findCloseEdges.rst
doc/version/pgr_full_version.rst
doc/version/pgr_version.rst
doc/withPoints/pgr_withPoints.rst
doc/withPoints/pgr_withPointsCost.rst
doc/withPoints/pgr_withPointsCostMatrix.rst
doc/withPoints/pgr_withPointsDD.rst
doc/withPoints/pgr_withPointsKSP.rst
doc/withPoints/pgr_withPointsVia.rst
docqueries/topology/degree.result
pgtap/topology/degree/types_check.pg
sql/topology/degree.sql

Work on #2369 
- more on fixing signatures

Release tasks 4

---

.github/workflows/windows.yml

Ports from #2361
Bumps [MarkusJx/install-boost](https://github.com/MarkusJx/install-boost) from 2.3.0 to 2.4.0.
- [Release notes](https://github.com/MarkusJx/install-boost/releases)
- [Commits](https://github.com/MarkusJx/install-boost/compare/v2.3.0...v2.4.0)
---
updated-dependencies:
- dependency-name: MarkusJx/install-boost dependency-type: direct:production update-type: version-update:semver-minor ...
Signed-off-by: dependabot[bot] <support@github.com>

Bump MarkusJx/install-boost from 2.3.0 to 2.4.0

---

include/c_common/get_check_data.h
src/common/get_check_data.c

Fixes # 972
- added developer doc of ```get_check_data.h```
- added developer doc of ```get_check_data.c```

added developers documentation

---

include/c_common/get_check_data.h
src/common/get_check_data.c

Fixes trailing spaces generated by contributor and some errors found when using Doxygen on files:
`src/common/get_check_data.c` 
`include/c_common/get_check_data.h`

[lint] removing trailing spaces

---

.github/workflows/ubuntu.yml
docqueries/astar/doc-aStarCostMatrix.result
docqueries/astar/doc-aStarCostMatrix.test.sql
docqueries/bdAstar/doc-pgr_bdAstarCostMatrix.result
docqueries/bdAstar/doc-pgr_bdAstarCostMatrix.test.sql

- do not use deprecated signature of tsp on examples of cost matrix

[docqueries][tsp] do not use deprecated tsp on examples of cost matrix

---

CMakeLists.txt
src/trsp/trsp.c

Fix centos build. References #2415 for pgRouting 3.4.2

---

include/bdAstar/pgr_bdAstar.hpp

[bdAstar] removing warning from clang

---

.github/workflows/centos.yml

Fixes #2452
This allows for running a self-hosted centos runner.
I have one on osgeo8 server, and tested on mine.  Seems to be stuck on some sort of permission issue in testing.  But I think it's something specific to my repo since the ubuntu ones have the same failure (but are okay on pgrouting org).
In order to use, we'll need to setup the runner configs as I have detailed here:
https://github.com/robe2/pgrouting/wiki/centtie-7-pgrouting-lxd-container#setup-as-a-runner
I gave @cvvergara  root rights to ssh root@osgeo8-centtie-7-pgrouting

Centos 7 self hosted runner

---

.github/workflows/centos.yml

Fixes #2452
We do sudo switch to postgres account, but unfortunately postgres doesn't have rights to the working directory of the runner.
The proposed fix here is to create a postgres database user account for the logged in runner, and then do the tests under then runner account instead of postgres.
Things additional I had to do:
1) Create database with same name as runner, cause by default psql will try to connect to the same named database unless a database is explicitly specified.  This was easier than changing all non-test db commands to use postgres database
2) I chose a very bad name for the runner account gha-pgrouting-runner, so had to escape user name in psql commands when creating user and db.
Tests run now but some are failing.  I think …

Centos 7 self hosted runner - fix permission issue on tests

---

.github/workflows/centos.yml

Fixes #2452
- Get rid of the cd ~, seems to be preventing the second command to drop from working

Centos 7 runner config fix 2

---

.github/workflows/centos.yml
pgtap/dijkstra/dijkstra/edge_cases/oneToOne_equiv_manyToMany.pg
pgtap/dijkstra/dijkstra/edge_cases/oneToOne_equiv_manyToOne.pg
tools/testers/setup_db.sh

Fixes #2452
-  Test whenever any code changes
-  I added the port back PGPORT, it is possible to have multiple versions of PostgreSQL installed on Centos, so if we ever do that, we'd have different versions running on different ports and will need this.
-  Change setup_db.sh to not rely on folder being part of a git repo (this is the part that was causing it to fail) maybe GHA does an export instead of a git clone.  Doing 
`git status`  within the centos 7, gives the same error in the pgrouting folder.
Anyway not good to rely on it being a git repo, cause I thing when apt packagers test, the way they export and import into theirs it might not be testing against a git repo
- Fix syntax errors in edge_cases tests

Centos 7 self hosted test fix 3 (for Develop)

---

tools/testers/setup_db.sh

Fixes #2452
- The recent change to setup_db.sh assumed testing will be done against a git repository.  
- In the case of self-hosted runner, this is not the case
- I suspect many packagers will also not be testing against a git repository, and may be using a tar ball instead. As such relying on this folder being part of a git repo will fail for them.
Note that this fix is a subset of #2469.  Those additional changes I don't think are needed to make it work for CentOS so don't need to be backported to main.

Directory should not rely on folder being part of a git repository (against main)

---

include/cpp_common/interruption.h

Tries to fix #2465 by including the complete files instead of doing selective copy paste based on the postgres version

[interruption] include the files instead of doing copy/paste

---

.github/workflows/ubuntu.yml

Cherry pick from #2460 and removing 18.04 no longer supported fro pgsql 15

Pgsql 15 and no 18.04 tests

---

doc/ksp/pgr_KSP.rst
locale/en/LC_MESSAGES/pgrouting_doc_strings.po
locale/pot/pgrouting_doc_strings.pot

[ksp][doc] fixing wording

---

ci/winnie/build_pgrouting.sh
ci/winnie/package_pgrouting.sh
tools/scripts/test_shell.sh

Fixes #2513 2513
- get rid of syntax checking 
- get rid of quotes in shell, as preventing from working

Fix winnie build

---

NEWS
doc/src/release_notes.rst
include/drivers/dijkstra/dijkstra_driver.h
src/dijkstra/dijkstra.c
src/dijkstra/dijkstra_driver.cpp

- Removing duplicated code due to the combinations query
- Updating release notes with missing notes

[dijkstra] Removing duplicated code

---

docqueries/astar/doc-aStarCost.result
docqueries/astar/doc-aStarCost.test.sql
docqueries/astar/doc-astar.result
docqueries/astar/doc-astar.test.sql
docqueries/bdAstar/doc-pgr_bdAstar.result
docqueries/bdAstar/doc-pgr_bdAstar.test.sql
docqueries/bdAstar/doc-pgr_bdAstarCost.result
docqueries/bdAstar/doc-pgr_bdAstarCost.test.sql
docqueries/lineGraph/proofOfConcept2.result
docqueries/lineGraph/proofOfConcept2.test.sql
docqueries/spanningTree/CMakeLists.txt

Fixes docqueries.
Some docqueries mark an error where they should not
This one will be fixed by GSoC student
docqueries/driving_distance/dijksraDD-issue729.result
In the following the `ERROR` is expected
docqueries/topologicalSort/doc-topologicalSort.result
docqueries/topology/createVertTab-any.result
docqueries/topology/doc-pgr_analyzeGraph.result
docqueries/topology/doc-pgr_createTopology.result
docqueries/topology/doc-pgr_createVerticesTable.result
docqueries/spanningTree/doc-pgr_randomSpanTree.result

Docqueries fix

---

README.md

master branch was renamed to main a while ago, but README still talking about master branch

Update README.md - master to main correction

---

NEWS
doc/src/release_notes.rst
docqueries/src/migration.result
docqueries/trsp/four_edges.result
docqueries/trsp/issue693.result
docqueries/trsp/issue704.result
docqueries/trsp/issue717.result
docqueries/trsp/trsp-any-02.result
docqueries/trsp/trsp-renumber.result
docqueries/trsp/trsp_vias-any-04.result
sql/driving_distance/_drivingDistance.sql
sql/driving_distance/_withPointsDD.sql
sql/driving_distance/withPointsDD.sql
sql/ksp/_withPointsKSP.sql
sql/ksp/withPointsKSP.sql
sql/max_flow/maxCardinalityMatch.sql
sql/trsp/pgr_trsp.sql
sql/trsp/pgr_trspViaEdges.sql
sql/trsp/pgr_trspViaVertices.sql
sql/withPoints/withPointsVia.sql

Messages and comments of deprecated functions:
Message:
`pgr_name(parameter's types) deprecated [function/signature] on v[number]`
Comments:
```
IS 'pgr_name deprecated [function/signature] on v[number]
- Documentation: ${PROJECT_DOC_LINK}/pgr_[new]name.html'
```
Comments:
`pgRouting internal function deprecated on v[number]`

Standardize deprecated messages

---

NEWS
doc/src/release_notes.rst
include/dominator/pgr_lengauerTarjanDominatorTree_driver.hpp
pgtap/dominator/lengauerTarjanDominatorTree/edge_cases.pg

Fixes #2565  .
- C/C++ Check the existence of the vertex and return empty set when it does not exist

Fix #2565 Returning empty results when vertex does not exist

---

.github/workflows/boost_version.yml
.github/workflows/check-queries.yml
.github/workflows/clang.yml
.github/workflows/doc-check.yml
.github/workflows/release.yml
.github/workflows/ubuntu.yml
.github/workflows/update-locale.yml
.github/workflows/update.yml
.github/workflows/website.yml

- Fix postgres version regex
In GitHub actions, Postgres version changed from:
```
psql (PostgreSQL) 14.9 (Ubuntu 14.9-1.pgdg22.04+1)
```
to
```
psql (PostgreSQL) 14.10 (Ubuntu 14.10-1.pgdg22.04+1)
```
PostgreSQL minor version can have more than 1 digits. Hence, changed regex from `\d` to `\d+` (here, `9` to `10`).

[actions] Fix postgres version regex

---

.github/workflows/boost_version.yml
.github/workflows/check-queries.yml
.github/workflows/clang.yml
.github/workflows/doc-check.yml
.github/workflows/release.yml
.github/workflows/ubuntu.yml
.github/workflows/update-locale.yml
.github/workflows/update.yml
.github/workflows/website.yml

- Fix postgres version regex
(Cherry-picking #2584 to `dev-4.0`)

[actions] Fix postgres version regex - cherrypick to dev-4.0

---

.github/workflows/boost_version.yml
.github/workflows/check-queries.yml
.github/workflows/clang.yml
.github/workflows/doc-check.yml
.github/workflows/release.yml
.github/workflows/ubuntu.yml
.github/workflows/update-locale.yml
.github/workflows/update.yml
.github/workflows/website.yml

- Fix postgres version regex
(Cherry-picking #2584 to `main`)

[actions] Fix postgres version regex - cherrypick to main

---

.github/workflows/doc-check.yml
doc/CMakeLists.txt

Creates a test for checking translations for chinese.
Expected check to "fail" but it will serve as a guide for translators on where they need to fix the translation to march sphinx syntax.

Test chinese

---

.github/workflows/boost_version.yml
.github/workflows/check-files.yml
README.md

This PR is about versions of PostgresSQL, boost, etc are supported on 3.7 

Deprecating min supported versions

---

include/c_types/path_rt.h
include/chinese/pgr_chinesePostman.hpp
pgtap/mincut/stoerWagner/compare_components.pg
src/astar/astar.c
src/bdAstar/bdAstar.c
src/bdDijkstra/bdDijkstra.c
src/bellman_ford/bellman_ford.c
src/bellman_ford/edwardMoore.c
src/breadthFirstSearch/binaryBreadthFirstSearch.c
src/chinese/chinesePostman_driver.cpp
src/common/basePath_SSEC.cpp
src/dagShortestPath/dagShortestPath.c
src/dijkstra/dijkstra.c
src/ksp/ksp.c
src/ksp/turnRestrictedPath.c
src/ksp/withPoints_ksp.c
src/max_flow/edge_disjoint_paths_driver.cpp
src/max_flow/pgr_maxflow.cpp
src/trsp/new_trsp.c
src/trsp/trsp_withPoints.c
src/withPoints/withPoints.c

- Removes `seq` from `Path_rt` to save some memory
- Fixes a case statement on pgtap/stoerWagner

Remove seq from path rt

---

.github/workflows/macos.yml

Supports #2618.
- Add macos-14 to macos CI
@cvvergara (CC: @pgRouting/admins)
I created this PR to `main`  branch with referring the following ubuntu's `matrix.os` setup,
so could you check this ?
https://github.com/pgRouting/pgrouting/blob/main/.github/workflows/ubuntu.yml#L27-L34

Add macos-14 to macos CI

---

.github/workflows/macos.yml
src/cpp_common/combinations.cpp

Fixes #2618, #2616.
- This is a same fix in #2619, but for `develop` branch.
- I just cherry-pick commit: https://github.com/pgRouting/pgrouting/commit/24d25b3e2ebfb1780d9fe92baff446e64fddc8b3, because merging `main` into `develop` seems not to be a current workflow.
- Fix macos-14 build error (#2616)

Add macos-14 to macos CI with fixing build error

---

.github/workflows/release.yml

- Update release GitHub actions to use NEWS.md instead of NEWS.
- Successor of #2601

Update release script to use NEWS.md on main

---

.github/workflows/release.yml

- Update release GitHub actions to use NEWS.md instead of NEWS.
- Successor of #2601

Update release script to use NEWS.md on develop

---

include/cpp_common/combinations.hpp
include/cpp_common/get_data.hpp
include/cpp_common/interruption.hpp
include/cpp_common/pgdata_getters.hpp
include/cpp_common/undefPostgresDefine.hpp
include/max_flow/pgr_maximumcardinalitymatching.hpp
src/cpp_common/get_check_data.cpp
src/cpp_common/pgdata_getters.cpp
src/max_flow/pgr_maxflow.cpp
tools/scripts/code_checker.sh

Fixes #2648 .
- postgres includes must be the first includes
- forward declaration of ArrayType  on header to avoid postgres includes
- wrapped a define because it was already defined
- Adjusted the code_checker script to ignore include order where applicable

Fix 2648 fail building under window mingw64

---

.github/workflows/macos.yml

Related with PR #2619.
- Recover macos test
- Update homebrew path after macOS Intel => Silicon update.
Example CI results:
- Before:
- Job: https://github.com/sanak/pgrouting/actions/runs/9336541789
- Total duration: 30m 6s
- After:
- Job: https://github.com/sanak/pgrouting/actions/runs/9336551609
- Total duration: 37m 18s
- Test summary: https://github.com/sanak/pgrouting/actions/runs/9336551609/job/25697256003#step:7:41034

Recover macos test

---

CMakeLists.txt
include/coloring/pgr_edgeColoring.hpp
include/tsp/tsp.hpp
src/alpha_shape/pgr_alphaShape.cpp
src/tsp/tsp.cpp

Boost provides a header, <boost/version.hpp>, which provides a BOOST_VERSION macro with the same semantics.
This change simplifies the build process and makes this project easier to incorporate in other build systems.
Fixes # .
-
-
-

Remove the Boost_VERSION_MACRO define from C++

---

CMakeLists.txt
NEWS.md
doc/src/release_notes.rst
include/coloring/pgr_edgeColoring.hpp
include/tsp/tsp.hpp
src/alpha_shape/pgr_alphaShape.cpp
src/tsp/tsp.cpp

ports latest changes in main branch v3.6.3 from the following PR:
- #2659 
- #2574 

Port main 3.6.3 changes to develop 3.7.0

---

NEWS.md
doc/src/release_notes.rst
docqueries/mincut/doc-stoerWagner.result
include/cpp_common/basePath_SSEC.hpp
include/cpp_common/rule.h
include/cpp_common/rule.hpp
include/trsp/pgr_trspHandler.h
include/yen/pgr_turnRestrictedPath.hpp
src/cpp_common/rule.cpp
src/ksp/turnRestrictedPath_driver.cpp
src/trsp/trspVia_driver.cpp
src/trsp/trspVia_withPoints_driver.cpp
src/trsp/trsp_driver.cpp
src/trsp/trsp_withPoints_driver.cpp

Fixes #2639 .
- add missing include

(C++) adding missing include to be fully compatible with C++13

---

.github/workflows/boost_version.yml
.github/workflows/release.yml
tools/scripts/test_license.sh

We have now a new language, so when releasing just create one documentation zip  instead of one per language

(CI) Just one file for all languages on release

---

.github/dependabot.yml
.github/scripts/tidy-vs-commit.sh
.github/workflows/boost_version.yml
.github/workflows/centos.yml
.github/workflows/doc-check.yml
.github/workflows/macos.yml
.github/workflows/release.yml
.github/workflows/update-locale.yml
.github/workflows/update.yml
.github/workflows/website.yml
NEWS.md
doc/src/release_notes.rst
include/cpp_common/rule.hpp
tools/scripts/test_license.sh

Porting fixes & changes on v3.6.3

Port fixes from master

---

NEWS.md
tools/release-scripts/notes2news.pl

- Removes trailing spaces generated on notes2news.pl

(tool) remove trailing space on NEWS.md

---

sql/common/pgrouting.control

The postgresl control file parser do not add up multiple occurences of the same keyword.  In practice it's not a big deal as plpgsql is installed by default.
Fixes # .
-
-
-

Fix requires

---

.github/workflows/update.yml

Testing the update of the extension with boost 1.56
Because the default boost version on the CI requires C++14 and older versions of boost use C++11 
and pgRouting older versions are not set up for C++14

Update test done with boost 56

---

NEWS.md
doc/src/release_notes.rst
include/cpp_common/Dmatrix.hpp

Fixes #2680 .
- add include directive
- Modify release notes and NEWS

Fix issue 2680 fails to compile under mingw64 gcc

---

.github/workflows/ubuntu.yml

Testing Postgres 17

---

NEWS.md
doc/src/release_notes.rst
include/trsp/trspHandler.hpp
src/trsp/trspHandler.cpp
src/trsp/trspVia_driver.cpp
src/trsp/trspVia_withPoints_driver.cpp
src/trsp/trsp_driver.cpp
src/trsp/trsp_withPoints_driver.cpp

Refine trsp handler class

---

NEWS.md
doc/src/release_notes.rst
include/cpp_common/to_postgres.hpp
include/metrics/betweennessCentrality.hpp
pgtap/metrics/betweennessCentrality/edge_cases.pg
src/metrics/betweennessCentrality.c
src/metrics/betweennessCentrality_driver.cpp

Fixes #2706.
- pgtap/metrics/betweennessCentrality/edge_cases.pg: removed excessive spaces and added some info
- include/metrics/betweennessCentrality.hpp: Cleaned up the code, removed the class
- Adjusted the driver and the C file

Fix #2706: pgr_betweennessCentrality

---

CMakeLists.txt
NEWS.md
README.md
doc/src/release_notes.rst

Fixes #2713
- Use old policies: CMP0148, CMP0144, CMP0167
- cmake min version set to 3.12

(build) Adding policies and cmake min version set to 3.12

---

ci/winnie/build_pgrouting.sh
tools/scripts/test_shell.sh

Fixes #2708
- Script for winnie is simplified
- TAPTEST variable added to verbose test a particular directory
- suitable for developers 
- DEBUG variable added 
- When true: Compilation is verbose, script variable contents are shown, build_type is "Debug"
- When false: build_type is "Release"
- BOOST_VER  to be captured, defaults to 1.78.0
Set up in winnie:
pgRouting_PGVersionEDB: TAPTEST = "", DEBUG= not set (aka false),  BOOST_VER=1.78.0
Branch develop: TAPTEST = "", DEBUG=true, BOOST_VER=1.78.0
Branch main: TAPTEST = "", DEBUG=true, BOOST_VER=1.78.0
For other branches like pgRouting_matrix_branch_tagged_3_7 will catch the defaults from pgRouting_PGVersionEDB on the new variables.

(CI/winnie) simplify code of winnie build script

---

tools/developer/run.sh
tools/developer/taptest.sh
tools/testers/doc_queries_generator.pl

Port Fixing docqueries generator flag -level & updating developer tools

---

README.md

Included a DOI badge linking to pgRouting's Zenodo record and added a citation section with BibTeX details for referencing the project in publications. This enhances documentation for scholarly use.
- adds DOI badge to readme
- adds CITATION section to readme.

Add DOI badge and citation details to README

---

NEWS.md
doc/_static/page_history.js
doc/src/migration.rst
doc/src/release_notes.rst
doc/topology/pgr_analyzeGraph.rst
doc/topology/pgr_analyzeOneWay.rst
doc/topology/pgr_createTopology.rst
doc/topology/pgr_createVerticesTable.rst
doc/topology/pgr_extractVertices.rst
docqueries/topology/createVertTab-any.result
docqueries/topology/createVerticesTable.result
locale/en/LC_MESSAGES/pgrouting_doc_strings.po
locale/pot/pgrouting_doc_strings.pot
pgtap/topology/analyzeGraph/issue_1311.pg
pgtap/topology/analyzeOneWay/edge_cases.pg
pgtap/topology/createVerticesTable/checkVertTab.pg
sql/common/utilities_pgr.sql
sql/topology/createverticestable.sql

Port deprecate pgr create vertices table

---

.gitignore
tools/developer/run.sh

- modify `.gitignore` to ignore taptest.sh located at the root of the repo;
- remove reference to the `vicky` user in the `run.sh` script;
- add an example to connect to a different version of PG than the last one.

Remove developer name from script

---

doc/src/pgRouting-introduction.rst
doc/src/proposed.rst
doc/src/release_notes.rst
doc/topology/topology-functions.rst
doc/utilities/pgr_separateCrossing.rst
doc/utilities/pgr_separateTouching.rst
docqueries/src/test.conf
locale/en/LC_MESSAGES/pgrouting_doc_strings.po
locale/pot/pgrouting_doc_strings.pot
sql/contraction/contractionHierarchies.sql
sql/contraction/deadEndContraction.sql
sql/contraction/linearContraction.sql
sql/lineGraph/lineGraph.sql
sql/max_flow/maxFlowMinCost.sql
sql/max_flow/maxFlowMinCost_Cost.sql
sql/metrics/betweennessCentrality.sql
sql/topology/nodeNetwork.sql
sql/utilities/separateCrossing.sql

ports commits from 
- #2876 
- #2874 
- #2878 

Port make official utilities and deprecate pgr node network

---

include/contraction/contractionGraph.hpp
include/contraction/contractionHierarchies.hpp
include/cpp_common/to_postgres.hpp
pgtap/contraction/contraction/types_check.pg
pgtap/utilities/findCloseEdges/edge_cases.pg
src/contraction/contractionHierarchies_driver.cpp

Work on #2870: Code Organization Issues.
- (pgtap/contraction) Fix pgr_contraction types check test
- (pgtap/findCloseEdges) fixing edge cases
- Reorganizing to_postgres.hpp & contractionHierarchies.hpp
- Using namespace detail for helper functions
- Moving perform_contractionHierarchies from to_postgres
- Using suitable names on functions
- Graph creation is done before calling contracion
- Fix clang tidy warnings & errors

Contraction: Fix Code Organization

---

.github/workflows/ubuntu.yml

Fixes # .
- Remove ubuntu 20.04 - no longer available on github
- Purge existing versions of PostgreSQL before install, so no issue with dependencies or having to check if port is not 5432
- Use trust gpg instead of deprecated apt key for adding repo
- Using apt.postgresql.org  --testing branch so can test pre-released versions like PG18
- Add PG18 to testing

Fix ubuntu ci and start testing PG18

---

NEWS.md
doc/coloring/coloring-family.rst
doc/coloring/pgr_edgeColoring.rst
doc/conf.py.in
doc/contraction/pgr_contraction.rst
doc/dijkstra/pgr_dijkstra.rst
doc/dijkstra/pgr_dijkstraCost.rst
doc/ksp/pgr_KSP.rst
doc/max_flow/pgr_maxFlow.rst
doc/max_flow/pgr_pushRelabel.rst
doc/src/migration.rst
doc/src/release_notes.rst
doc/trsp/pgr_trspVia.rst
docqueries/coloring/edgeColoring.pg
docqueries/coloring/edgeColoring.result
pgtap/coloring/edgeColoring/edge_cases.pg
pgtap/coloring/edgeColoring/types_check.pg
sql/coloring/edgeColoring.sql
sql/scripts/build-extension-update-files.pl

Fixes #2924 
- Standardizing output columns pgr_edgeColoring to (edge,color)
- Adding migration guide of pgr_edgeColoring
- News and release notes about pgr_edgeColoring
- NEWS and release notes : Adding missing information
- 

Fix 2924 standardize pgr edge coloring

---

NEWS.md
doc/coloring/coloring-family.rst
doc/coloring/pgr_bipartite.rst
doc/conf.py.in
doc/src/migration.rst
doc/src/release_notes.rst
docqueries/coloring/bipartite.pg
docqueries/coloring/bipartite.result
pgtap/coloring/bipartite/types_check.pg
sql/coloring/bipartite.sql
sql/scripts/build-extension-update-files.pl

Fixes # .
- Updating News about pgr_bipartite
- `pgr_bipartite`: updating documentation
- Standardizing output columns pgr_bipartite to `(node,color)`

Issue 2926 standardize pgr bipartite

---

pgtap/ordering/topologicalSort/edge_cases.pg

- Edge cases tests for `pgr_topologicalSort`

Test topological sort
