pgRouting/pgrouting

- doc/src/changelog/2_1_0.rst
- doc/test/alphashape-any.test.sql
- src/driving_distance/doc/dd_alphashape.rst
- src/driving_distance/doc/dd_points_as_polygon.rst
I updated `pgr_alphaShape` and `pgr_pointsAsPolygon` documents (#383).
Could someone check this ?
Thanks,
> Updated 'pgr_alphaShape' and 'pgr_pointsAsPolygon' documents

- src/contraction/src/CMakeLists.txt
- src/contraction/src/src/mydijkstra/src/dijkstra_function.cpp
> Contraction 2.2.0

- doc/src/tutorial/tutorial.rst
Not wanting to be pedantic - this is just my first pull request (for any project), so I wanted to start with something simple that isn't going to break your project!
I'm starting the tutorials, and I'm looking forward to learning the power of pgrouting :smile:
> small grammatical corrections.

- src/driving_distance/sql/routing_dd.sql
Fixes #493 .
Missing alpha parameter.
> Develop - Missing alpha parameter at pgr_pointsaspolygon

- src/withPoints/doc/pgr_withPoints.rst
- src/withPoints/doc/pgr_withPointsCost.rst
- src/withPoints/doc/pgr_withPointsDD.rst
- src/withPoints/doc/pgr_withPointsKSP.rst
> Fixed syntax and grammar errors in the documentation of pgr_withPoints family

- src/contraction/doc/contraction.rst
- src/proposed.rst
> Dev 2.2 contract doc

- src/contraction/src/contraction_structs.hpp
- src/contraction/src/pgr_contract.hpp
> Added new classes for contraction part-1

- src/contraction/src/contraction_structs.hpp
- src/contraction/src/pgr_contract.hpp
> Added new classes for contraction part-3

- src/contraction/src/pgr_contract.hpp
> Added files for testing proof of concept part-2

- src/dijkstra/src/pgr_dijkstra.hpp
- src/driving_distance/test/pgtap/issue-519.sql
- tools/testers/pg_prove_tests.sh
Fixes #519 .
- fix for 519
- pgtap test for issue 519
> V2.2/hot fix/issue519

- src/topology/doc/pgr_analyzeGraph.rst
Fixes #555 .
- Fixed spellings errors of analyzeGraph.
- Fixed spelling of pgr_createTopology function.
> Fixed docs for analyzeGraph

- 2.2/en/src/topology/doc/pgr_analyzeGraph.html
Updated gh-pages for analyseGraph. See issue #555
> Updated analyseGraph gh-pages

- doc/src/installation/installation.rst
> fixing #543

- src/common/src/identifiers.hpp
- src/contraction/src/contractGraph_driver.cpp
- src/contraction/src/pgr_contract.hpp
- src/contraction/src/pgr_contractionGraph.hpp
- src/contraction/src/pgr_linearContraction.hpp
- src/contraction/test/pgtap/contraction_cycle_directed.sql
- src/contraction/test/pgtap/contraction_cycle_undirected.sql
Fixes # .
- Added pgtap tests for testing contraction cycle
- Documentation of identifiers and contraction graph class 
> Unit tests and documentation

- src/topology/sql/nodeNetwork.sql
- src/topology/test/nodeNetwork-any.result
> fixed #612 nodeNetwork in develop

- src/topology/sql/nodeNetwork.sql
- src/topology/test/nodeNetwork-any.result
> fixed #612 nodeNetwork

- src/tsp/doc/pgr_tsp.rst
> fixed a name

- src/common/src/identifiers.hpp
- src/contraction/test/pgtap/directed_dead_end.sql
- src/contraction/test/pgtap/directed_linear.sql
- src/contraction/test/pgtap/undirected_dead_end.sql
- src/contraction/test/pgtap/undirected_linear.sql
Fixes # .
- Added missing header
- Modified pgtap tests by using sample data
-
> Travis build passed

- src/contraction/doc/contraction.rst
- src/contraction/doc/pgr_contractGraph.rst
- src/contraction/src/contraction.dox
> Updated developer documentation

- doc/conf.py.in
- src/contraction/doc/contraction.rst
> making graphviz work ons sphinx

- src/contraction/doc/contraction.rst
> Updated user documentation

- src/max_flow/demo/slide_demo.sql
> Added code for demo

- src/contraction/doc/contraction.rst
- src/contraction/doc/pgr_contractGraph.rst
> Updated documentation

- src/contraction/doc/contraction.rst
> Removed syntax error in documentation

- .travis.yml
- VERSION
- src/trsp/test/pgtap/no-restrictions-compare-dijkstra-directed.test.sql
- src/trsp/test/pgtap/no-restrictions-compare-dijkstra-undirected.test.sql
- tools/testers/pg_prove_tests.sh
- tools/travis/install-doxygen.sh
- tools/travis/install-postgres.sh
- tools/travis/test-documentation.sh
Fixes  travis & appveyor tests due to changes on versions of postgres & postGIS
>  travis & appveyor tests 

- src/vrppdtw/doc/pgr_gsoc_vrppdtw.rst
> Fix sql column names in vpr doc

- src/trsp/doc/pgr_trsp.rst
> minor typo correction

- VERSION
- src/driving_distance/test/issue729.result
- src/driving_distance/test/issue729.test.sql
- src/driving_distance/test/test.conf
Proves that #729 is being fixed on 2.4
> adding test for #729

- VERSION
- src/trsp/src/trsp.c
Fixes an unwanted mnotice mssage on windows
> trsp: removing notice only shown on windows

- src/trsp/src/GraphDefinition.cpp
- src/trsp/src/GraphDefinition.h
- src/trsp/src/trsp.h
Fixes :
- Change for loop to range loop
- use **auto**
- Change **int** to **long**
> Fixing all warnings in /src/trsp/src/GraphDefinition.cpp

- src/trsp/src/GraphDefinition.cpp
- src/trsp/src/GraphDefinition.h
Fixes:
-change ```ruleL_i``` to ```rule```
-change for loop to range loop
-remove unused code
> Fix bad variable name

- src/vrp_basic/src/VRP_Solver.cpp
Fix: 
- Updating for loop to range-for loop 
> Updating for loop to range-for loop

- index.html
Fixes the following issues:
* indention
* missing `</div>` at the end (need to make sure, if this is right, or if it should be inserted before the footer)
* changes `h4` to `h3`
> Fixing HTML

- src/bdDijkstra/src/pgr_bdDijkstra.hpp
Try to fix #767 and https://github.com/Homebrew/homebrew-core/pull/11365.
> Updated clear call on member (#767)

- VERSION
- src/withPoints/src/many_to_many_withPoints_driver.cpp
> trying to fix 769

- doc/src/pgRouting-installation.rst
> Fix typo in pgRouting-installation.rst

- doc/src/pgRouting-installation.rst
Opened on the advice of @cvvergara (on #779)
- Fix small typo
> Fix typo in pgRouting-installation.rst (develop)

- README.md
Minor text updates (fixed broken table, invalid link).
Fixes #<n/a>
- Fix broken table (extra newline)
- Fix broken link (`http://.postgis.net/windows_downloads`)
- Changed capitalization of `perl`.
> Fix broken table HTML, broken link.

- src/trsp/src/GraphDefinition.h
src/trsp/src/GraphDefinition.h
> Lint the code for TRSP GraphDefinition.h based on the C and C++ google guidelines. 

- src/trsp/src/trsp_driver.h
Fixes # .
- Linted src/trsp/src/trsp_driver.h
-
-
> Linted trsp_driver.h

- src/areaContraction/src/areaContraction_driver.cpp
Fixes [#19](https://github.com/daas-ankur-shukla/pgrouting/issues/19) [#22](https://github.com/daas-ankur-shukla/pgrouting/issues/22)
- added borderVertice_size variable to areaContraction_driver.cpp file
- Fixes Travis and Appveyor fails
- No tests in tests.conf
> Fixed Travis and Appveyor for pgr_areaContraction function

- configuration.conf
> Table values

- include/drivers/dijkstraTRSP/dijkstraTRSP_driver.h
- sql/dijkstraTRSP/dijkstraTRSP.sql
- src/dijkstraTRSP/src/dijkstraTRSP.c
- src/dijkstraTRSP/src/dijkstraTRSP_driver.cpp
- src/dijkstraTRSP/test/doc-dijkstraTRSP.result
- src/dijkstraTRSP/test/doc-dijkstraTRSP.test.sql
- src/dijkstraTRSP/test/pgtap/dijkstraTRSP-compare-dijkstra.sql
- src/dijkstraTRSP/test/pgtap/dijkstraTRSP-innerQuery.sql
- src/dijkstraTRSP/test/pgtap/dijkstraTRSP-typesCheck.sql
- src/dijkstraTRSP/test/pgtap/empty_set.sql
- src/dijkstraTRSP/test/pgtap/empty_set_NO_default_strict.sql
- src/dijkstraTRSP/test/pgtap/empty_set_default_strict.sql
- src/dijkstraTRSP/test/pgtap_design.result
- src/dijkstraTRSP/test/pgtap_design.test.sql
- tools/testers/inner_styles.sql
- tools/testers/sampledata.sql
> Updating the upstream branch

- doc/pickDeliver/VRP-category.rst
- doc/vrppdtw/CMakeLists.txt
> removing the vrppdtw documentation

- doc/queries/doc-pgr_connectedComponentsV.queries
- doc/src/proposed.rst
- src/components/test/doc-pgr_connectedComponentsV.result
- src/components/test/doc-pgr_connectedComponentsV.test.sql
- src/components/test/test.conf
picked those two
```
@XJTUmg     XJTUmg     add connectedComponentsV into proposed.rst         
e8e7137
@XJTUmg     XJTUmg     added q2 & q3         
6c6ad42
```
> Backup, git cherry-pick

- doc/queries/doc-pgr_connectedComponentsV.queries
- include/components/pgr_components.hpp
- include/drivers/components/strongComponentsV_driver.h
- sql/components/CMakeLists.txt
- sql/components/strongComponentsV.sql
- src/components/src/CMakeLists.txt
- src/components/src/connectedComponentsV.c
- src/components/src/connectedComponentsV_driver.cpp
- src/components/src/strongComponentsV.c
- src/components/src/strongComponentsV_driver.cpp
- src/components/test/doc-pgr_connectedComponentsV.result
- src/components/test/doc-pgr_connectedComponentsV.test.sql
> Implement pgr_strongComponentsV

- doc/queries/doc-pgr_biconnectedComponents.queries
- include/components/pgr_components.hpp
- include/components/pgr_componentsGraph.hpp
- src/components/src/biconnectedComponents_driver.cpp
- src/components/src/connectedComponentsV_driver.cpp
- src/components/test/doc-pgr_biconnectedComponents.result
- src/components/test/doc-pgr_biconnectedComponents.test.sql
- src/components/test/test.conf
> Extend Pgr_base_graph to fix duplicates

- doc/components/pgr_connectedComponentsV.rst
experimenting handling 2 branches, blank line represents many changes in the file
> Experimenting handling 2 branches

- tools/winnie/package_pgrouting.sh
Need to change packaging to use new paths.
Fixes # .
-
-
-
> Path to sql scripts and control file changed

- CODE_OF_CONDUCT.md
> using osgeo code of conduct

- ci/appveyor/install.bat
Posgis version 2.3.1 is now in archives
> fixing appveyor on master

- doc/components/CMakeLists.txt
- doc/components/components-family.rst
- doc/components/pgr_articulationPoints.rst
- doc/components/pgr_biconnectedComponents.rst
- doc/components/pgr_bridges.rst
- doc/components/pgr_connectedComponents.rst
- doc/components/pgr_connectedComponentsV.rst
- doc/components/pgr_strongComponents.rst
- doc/queries/CMakeLists.txt
- doc/queries/doc-pgr_connectedComponents.queries
- doc/queries/doc-pgr_strongComponents.queries
- doc/src/proposed.rst
- doc/src/release_notes.rst
- include/components/pgr_components.hpp
- include/drivers/components/connectedComponents_driver.h
- include/drivers/components/strongComponents_driver.h
- sql/components/CMakeLists.txt
- sql/components/connectedComponents.sql
- sql/components/strongComponents.sql
- src/components/src/CMakeLists.txt
- src/components/src/connectedComponents.c
- src/components/src/connectedComponents_driver.cpp
- src/components/src/strongComponents.c
- src/components/src/strongComponents_driver.cpp
- src/components/test/doc-pgr_connectedComponents.result
- src/components/test/doc-pgr_connectedComponents.test.sql
- src/components/test/doc-pgr_strongComponents.result
- src/components/test/doc-pgr_strongComponents.test.sql
- src/components/test/test.conf
> Improve the code and docs

- doc/components/pgr_articulationPoints.rst
- doc/components/pgr_biconnectedComponents.rst
- doc/components/pgr_bridges.rst
- doc/components/pgr_connectedComponents.rst
- doc/components/pgr_strongComponents.rst
> Fix Documentation bugs of components functions

- doc/alpha_shape/pgr_alphaShape.rst
- doc/astar/pgr_aStar.rst
- doc/astar/pgr_aStarCost.rst
- doc/bdAstar/pgr_bdAstar.rst
- doc/bdAstar/pgr_bdAstarCost.rst
> Fix bullets issues

- tools/template/create.sh
Fixes # .
- Changed code in create.sh file which now generates a template function according to the new directory structure
-
-
> Updated template code according to the new directory structure

- doc/withPoints/withPoints-family.rst
> Fixed typos

- doc/allpairs/allpairs-family.rst
- doc/allpairs/pgr_floydWarshall.rst
> [WIP] Update allpairs-family.rst

- include/allpairs/pgr_allpairs.hpp
> Improve code of Class Pgr_allpairs issue-969 #974

- 404.html
404 Error Page for pgRouting
Created new 404 error page
> 404 Error Page

- .travis.yml
- VERSION
> removing the edge group

- .travis.yml
- VERSION
- tools/testers/algorithm-tester.pl
- tools/testers/pg_prove_tests.sh
> Fixing Algorithm tester for pg > 10

- ci/bessie/regress.sh
- ci/bessie32/regress.sh
> Bessie develop

- include/c_common/get_check_data.h
- src/common/get_check_data.c
Fixes #issue972 .
These commit contain doxygen documentation of get_check_data.c.
https://apsnazii.github.io/pgRouting/doxygen/html/get__check__data_8c.html
For doxygen documentation of arrays_input.c
https://apsnazii.github.io/pgRouting/doxygen/html/arrays__input_8c.html
> Doxygen documentation of get_check_data

- doc/src/pgRouting-introduction.rst
This PR updates the contributor section of the introduction documentation
> Updating contributors for this release

- include/c_types/pgr_components_rt.h
- include/drivers/components/articulationPoints_driver.h
- include/drivers/components/biconnectedComponents_driver.h
- include/drivers/components/bridges_driver.h
- include/drivers/components/connectedComponents_driver.h
- include/drivers/components/strongComponents_driver.h
- sql/components/articulationPoints.sql
- sql/components/biconnectedComponents.sql
- sql/components/bridges.sql
- sql/components/connectedComponents.sql
- sql/components/strongComponents.sql
- src/components/articulationPoints.c
- src/components/articulationPoints_driver.cpp
- src/components/biconnectedComponents.c
- src/components/biconnectedComponents_driver.cpp
- src/components/bridges.c
- src/components/bridges_driver.cpp
- src/components/connectedComponents.c
- src/components/connectedComponents_driver.cpp
- src/components/strongComponents.c
- src/components/strongComponents_driver.cpp
refer to https://github.com/pgRouting/pgrouting/pull/1025
> Fix components licenses

- include/drivers/prim/prim_driver.h
- sql/prim/CMakeLists.txt
- sql/prim/prim.sql
- src/prim/CMakeLists.txt
- src/prim/prim.c
- src/prim/prim_driver.cpp
> [WIP] Implementation of PRIM Algorithm 

- configuration.conf
- doc/costFlow/CMakeLists.txt
- doc/costFlow/costFlow-family.rst
- doc/costFlow/pgr_minCostMaxFlow.rst
- doc/costFlow/pgr_minCostMaxFlow_Cost.rst
- doc/queries/CMakeLists.txt
- doc/queries/doc-pgr_minCostMaxFlow.queries
- doc/queries/doc-pgr_minCostMaxFlow_Cost.queries
- doc/src/pgRouting-concepts.rst
- doc/src/proposed.rst
- include/costFlow/pgr_costFlowGraph.hpp
- include/costFlow/pgr_minCostMaxFlow.hpp
- sql/costFlow/minCostMaxFlow.sql
- src/common/edges_input.c
- src/costFlow/minCostMaxFlow.c
- src/costFlow/minCostMaxFlow_driver.cpp
- test/costFlow/doc-pgr_minCostMaxFlow.result
- test/costFlow/doc-pgr_minCostMaxFlow.test.sql
- test/costFlow/doc-pgr_minCostMaxFlow_Cost.result
- test/costFlow/doc-pgr_minCostMaxFlow_Cost.test.sql
- test/costFlow/test.conf
> [WIP] Documentation of costFlow functions

- pgtap/costFlow/costFlow-innerQuery.sql
- pgtap/costFlow/costFlow-types-check.sql
- pgtap/costFlow/costFlow_Cost-innerQuery.sql
- pgtap/costFlow/costFlow_Cost-types-check.sql
- sql/costFlow/CMakeLists.txt
- sql/costFlow/minCostMaxFlow.sql
- sql/costFlow/pgr_minCostMaxFlow.sql
- sql/costFlow/pgr_minCostMaxFlow_Cost.sql
- tools/testers/inner_styles.sql
> [WIP] pgTAP tests for costFlow functions

- doc/prim/doc-pgr_prim.queries
- doc/prim/pgr_prim.rst
- include/c_types/pgr_prim_t.h
- include/drivers/prim/prim_driver.h
- include/prim/pgr_prim.hpp
- pgtap/prim/compare.test.sql
- pgtap/prim/prim-innerQuery.sql
- pgtap/prim/prim-types-check.sql
- sql/prim/CMakeLists.txt
- sql/prim/_prim.sql
- sql/prim/prim.sql
- src/prim/prim.c
- src/prim/prim_driver.cpp
- test/prim/doc-prim.result
- test/prim/doc-prim.test.sql
- tools/testers/inner_styles.sql
Default value of root_vertex is -1 for MST of disconnected graph.
> [WIP] PgTap Tests for pgr_prim

- include/drivers/prim/kruskal_driver.h
- include/prim/pgr_kruskal.hpp
- sql/prim/CMakeLists.txt
- sql/prim/kruskal.sql
- src/prim/CMakeLists.txt
- src/prim/kruskal.c
- src/prim/kruskal_driver.cpp
> [WIP] Basic code of pgr_kruskal

- doc/bellman_ford/doc-pgr_bellman_ford.queries
- doc/bellman_ford/pgr_bellman_ford.rst
- include/bellman_ford/pgr_bellman_ford.hpp
- include/drivers/bellman_ford/bellman_ford_driver.h
- sql/bellman_ford/_bellman_ford.sql
- sql/bellman_ford/bellman_ford.sql
- src/bellman_ford/bellman_ford.c
- src/bellman_ford/bellman_ford_driver.cpp
- **One to One**
pgr_bellman_ford (edge_sql, start_vid, end_vid, directed = true)
RETURNS SET OF (seq, path_seq, node, edge, cost, agg_cost) OR EMPTY SET
- **One to Many**
pgr_bellman_ford (edge_sql, start_vid, end_vids, directed = true)
RETURNS SET OF (seq, path_seq, end_vid, node, edge, cost, agg_cost) OR EMPTY SET
- **Many to One**
pgr_bellman_ford (edge_sql, start_vids, end_vid, directed = true)
RETURNS SET OF (seq, path_seq, start_vid, node, edge, cost, agg_cost) OR EMPTY SET
- **Many to Many**
pgr_bellman_ford (edge_sql, start_vids, end_vids, directed = true)
RETURNS SET OF (seq, path_seq, start_vid, end_vid, node, edge, cost, agg_cost) OR EMPTY SET
> [WIP] Full Implementation of pgr_bellman_ford with Documentation

- include/drivers/ChPP/directedChPP_driver.h
- sql/ChPP/directedChPP.sql
- sql/ChPP/pgr_directedChPP.sql
- sql/ChPP/pgr_directedChPP_Cost.sql
- src/ChPP/directedChPP.c
- src/ChPP/directedChPP_driver.cpp
> Implement pgr_directedChPP framework

- doc/bellman_ford/doc-pgr_bellman_ford.queries
- doc/bellman_ford/pgr_bellman_ford.rst
- include/bellman_ford/bellman_ford_testing.cpp
- include/bellman_ford/pgr_bellman_ford.hpp
- include/cpp_common/pgr_base_graph.hpp
- pgtap/bellman_ford/bellman_ford-compare-dijkstra.sql
- pgtap/bellman_ford/bellman_ford-innerQuery.sql
- pgtap/bellman_ford/bellman_ford-typesCheck.sql
- sql/bellman_ford/_bellman_ford.sql
- sql/bellman_ford/bellman_ford.sql
- src/bellman_ford/bellman_ford_driver.cpp
- test/bellman_ford/doc-bellman_ford.result
- test/bellman_ford/doc-bellman_ford.test.sql
> [WIP] Implementation of pgrBellmanFord

- include/bellman_ford/pgr_bellman_ford.hpp
- include/cpp_common/pgr_base_graph.hpp
- include/drivers/bellman_ford/bellman_ford_neg_driver.h
- pgtap/bellman_ford/bellman_ford-innerQuery.sql
- sql/bellman_ford/CMakeLists.txt
- sql/bellman_ford/_bellman_ford_neg.sql
- sql/bellman_ford/bellman_ford_neg.sql
- src/bellman_ford/CMakeLists.txt
- src/bellman_ford/bellman_ford_driver.cpp
- src/bellman_ford/bellman_ford_neg.c
- src/bellman_ford/bellman_ford_neg_driver.cpp
Tasks
Branch: https://github.com/codeSG/pgrouting/tree/bf-negative
> [WIP] Implementation of pgr_bellmanFord function

- doc/bellman_ford/CMakeLists.txt
- doc/bellman_ford/pgr_bellmanFord.rst
- doc/queries/CMakeLists.txt
- doc/queries/doc-bellman_ford.queries
- doc/queries/doc-pgr_bellman_ford.queries
- doc/src/proposed.rst
- include/bellman_ford/pgr_bellman_ford.hpp
- src/bellman_ford/bellman_ford.c
- src/bellman_ford/bellman_ford_neg.c
> Fix Compile and Documentation Warnings

- configuration.conf
- include/c_types/pgr_stoerWagner_t.h
- include/drivers/mincut/stoerWagner_driver.h
- include/mincut/pgr_stoerWagner.hpp
- pgtap/mst/compare.test.sql
- pgtap/mst/kruskal-innerQuery.sql
- pgtap/mst/kruskal-types-check.sql
- sql/mincut/CMakeLists.txt
- sql/mincut/stoerWagner.sql
- src/mincut/CMakeLists.txt
- src/mincut/stoerWagner.c
- src/mincut/stoerWagner_driver.cpp
- tools/testers/inner_styles.sql
> pgTAP for pgr_kruskal and Implementation of pgr_stoerWagner

- include/ChPP/pgr_directedChPP.hpp
- src/ChPP/directedChPP_driver.cpp
> [WIP] Implementation of pgr_directedChPP

- src/parallel/README.md
- src/parallel/boost_mpi_test.cpp
- src/parallel/mpi_test.cpp
- src/parallel/test_graph_small_1.gr
- src/parallel/test_graph_small_2.gr
> Experimentation of parallel boost graph

- include/ChPP/pgr_directedChPP.hpp
- include/costFlow/pgr_minCostMaxFlow.hpp
- src/ChPP/directedChPP_driver.cpp
> [ChPP]Bug Fix

- include/c_types/pgr_randomSpanningTree_t.h
- include/drivers/mst/randomSpanningTree_driver.h
- include/mst/pgr_randomSpanningTree.hpp
- sql/mst/CMakeLists.txt
- sql/mst/randomSpanningTree.sql
- src/mst/CMakeLists.txt
- src/mst/randomSpanningTree.c
- src/mst/randomSpanningTree_driver.cpp
> [WIP] Basic code for pgr_randomSpanningTree

- configuration.conf
- doc/dagShortestPath/CMakeLists.txt
- doc/dagShortestPath/doc-pgr_dagShortestPath.queries
- doc/dagShortestPath/pgr_dagShortestPath.rst
- doc/queries/doc-dagShortestPath.queries
- doc/queries/doc-pgr_dagShortestPath.queries
- doc/src/proposed.rst
- include/dagShortestPath/pgr_dagShortestPath.hpp
- include/drivers/dagShortestPath/dagShortestPath_driver.h
- sql/dagShortestPath/_dagShortestPath.sql
- sql/dagShortestPath/dagShortestPath.sql
- src/dagShortestPath/dagShortestPath.c
- src/dagShortestPath/dagShortestPath_driver.cpp
- test/dagShortestPath/doc-dagShortestPath.result
- test/dagShortestPath/doc-dagShortestPath.test.sql
- test/dagShortestPath/test.conf
```
pgr_dagShortestPath(edges_sql, start_vid,  end_vid)
pgr_dagShortestPath(edges_sql, start_vids,  end_vid)
pgr_dagShortestPath(edges_sql, start_vid,  end_vids)
pgr_dagShortestPath(edges_sql, start_vids,  end_vids)
RETURNS SET OF (seq, path_seq, node, edge, cost, agg_cost)
OR EMPTY SET
```
> [WIP] Implemention of pgr_dagShortestPath

- include/c_types/pgr_costFlow_t.h
- include/drivers/ChPP/directedChPP_driver.h
- include/drivers/costFlow/minCostMaxFlow_driver.h
- src/ChPP/directedChPP.c
- src/costFlow/minCostMaxFlow.c
> compiled with c++-7

- include/c_types/pgr_kruskal_t.h
- include/c_types/pgr_prim_t.h
- include/c_types/pgr_randomSpanningTree_t.h
- include/c_types/pgr_stoerWagner_t.h
- include/drivers/mincut/stoerWagner_driver.h
- include/drivers/mst/kruskal_driver.h
- include/drivers/mst/prim_driver.h
- include/drivers/mst/randomSpanningTree_driver.h
- src/mincut/stoerWagner.c
- src/mst/kruskal.c
- src/mst/prim.c
- src/mst/randomSpanningTree.c
* Add `#include <stdbool.h>` in file `src/foo/foo.c1`
* Add this code in file `src/foo/foo_driver.c`
```
/* for size-t */
#ifdef __cplusplus
#else
#endif
```
> Compile my work with gcc7

- include/drivers/bellman_ford/bellman_ford_driver.h
- include/drivers/bellman_ford/bellman_ford_neg_driver.h
- include/drivers/dagShortestPath/dagShortestPath_driver.h
- pgtap/dagShortestPath/dagShortestPath-innerQuery.sql
- pgtap/dagShortestPath/dagShortestPath-typesCheck.sql
- src/bellman_ford/bellman_ford.c
- src/bellman_ford/bellman_ford_neg.c
- src/dagShortestPath/dagShortestPath.c
* Add `#include <stdbool.h>` in file `src/foo/foo.c1`
* Add this code in file `src/foo/foo_driver.c`
```
/* for size-t */
#ifdef __cplusplus
#else
#endif
``` 
**Changes done for:**
> Compile my project work with gcc7

- README.md
I updated the branch list in `README.md`, but I'm not completly sure weather this really represents the current branch system. ;)
> Updated README.md to represent branches

- VERSION
- doc/ChPP/ChPP-family.rst
- doc/ChPP/pgr_directedChPP.rst
- doc/ChPP/pgr_directedChPP_Cost.rst
- doc/queries/CMakeLists.txt
- doc/queries/doc-kruskal.queries
- doc/queries/doc-pgr_dagShortestPath.queries
- doc/queries/doc-pgr_directedChPP.queries
- doc/queries/doc-pgr_directedChPP_Cost.queries
- doc/queries/doc-pgr_turnRestrictedPath.queries
- doc/queries/doc-prim.queries
- doc/queries/doc-stoerWagner.queries
- doc/src/proposed.rst
Fixes documentation issues
https://travis-ci.org/pgRouting/pgrouting/jobs/429338161#L1551
Note: the `pgRouting-concepts.rst:14: ERROR: Unknown target name: "many to one".` kind of issues are not fixed
> adding missing files & fixing some doc issues

- doc/costMatrix/pgr_dijkstraCostMatrix.rst
- doc/dijkstra/dijkstra-family.rst
- doc/dijkstra/pgr_dijkstraCost.rst
- doc/dijkstra/pgr_dijkstraVia.rst
- doc/src/proposed.rst
- doc/tsp/pgr_TSP.rst
Fixes # 1103
- Standardization of titles
-
-
> pgr_dijkstraCostMatrix-doc

- doc/dijkstra/pgr_dijkstraCost.rst
Fixes # 1104
-Titles standarization
-
-
> Dijk cost doc

- doc/bdDijkstra/bdDijkstra-family.rst
- doc/bdDijkstra/pgr_bdDijkstra.rst
- doc/bdDijkstra/pgr_bdDijkstraCost.rst
- doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
- doc/src/routingFunctions.rst
Fixes # 1110
-fixes on bdDijkstra
> Bddijkstra doc

- doc/alpha_shape/pgr_alphaShape.rst
modified:   doc/alpha_shape/pgr_alphaShape.rst
Fixes # 1100
-Standarization of titles
> [pgr_alphaShape] Standarization of titles

- doc/astar/pgr_aStar.rst
- doc/components/components-family.rst
- doc/components/pgr_articulationPoints.rst
- doc/src/index.rst
- doc/src/pgRouting-concepts.rst
- doc/src/proposed.rst
- doc/topology/pgr_createTopology.rst
- doc/topology/pgr_createVerticesTable.rst
- doc/topology/topology-functions.rst
Fixes # 1100
-fixed errors ref/doc
-standarization of titles in articulationPoints
-standarization of titles in aStar
> Documentation fixes

- tools/template/doc/pgr_function1.rst
Fixes #1100
-Standarized template 
> Doc function1

- doc/bellman_ford/pgr_bellmanFord.rst
- doc/components/components-family.rst
- doc/components/pgr_biconnectedComponents.rst
- doc/components/pgr_bridges.rst
- doc/components/pgr_connectedComponents.rst
- doc/contraction/pgr_contractGraph.rst
- doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
- doc/dagShortestPath/pgr_dagShortestPath.rst
- doc/max_flow/pgr_boykovKolmogorov.rst
- doc/topology/pgr_createTopology.rst
- doc/topology/pgr_createVerticesTable.rst
Fixes #1100 . on several files
> [documentation] Fixing several files

- doc/costMatrix/pgr_withPointsCostMatrix.rst
- doc/src/pgRouting-concepts.rst
- doc/withPoints/pgr_withPoints.rst
- doc/withPoints/pgr_withPointsCost.rst
- doc/withPoints/pgr_withPointsDD.rst
- doc/withPoints/pgr_withPointsKSP.rst
Fixes #1100
-Standarizing titles
> Doc withPoints

- doc/mst/pgr_randomSpanTree.rst
Fixes #1100
-Standarized template
> RandomSpanTree

- doc/lineGraph/pgr_lineGraph.rst
- doc/lineGraph/pgr_lineGraphFull.rst
Fixes #1100
-standarized titles
> LineGraph-doc

- doc/costFlow/pgr_minCostMaxFlow.rst
- doc/costFlow/pgr_minCostMaxFlow_Cost.rst
- doc/src/pgRouting-concepts.rst
Fixes #1100
-Standarizing titles
> MinCostMaxFlow

- doc/ChPP/pgr_directedChPP.rst
- doc/ChPP/pgr_directedChPP_Cost.rst
Fixes # 1100
- Standarizing titles
> directedChPP- doc

- doc/mst/pgr_kruskal.rst
- doc/mst/pgr_prim.rst
Fixes # 1100
- Standarizing titles
> [spanningTree-doc] Standarizing titles

- doc/alpha_shape/pgr_alphaShape.rst
- doc/astar/pgr_aStar.rst
- doc/astar/pgr_aStarCost.rst
- doc/components/pgr_articulationPoints.rst
- doc/topology/pgr_analyzeGraph.rst
- doc/topology/pgr_analyzeOneWay.rst
Fixes #1100
- Fixed first section
> Check first section

- doc/astar/pgr_aStar.rst
- doc/astar/pgr_aStarCost.rst
- doc/astar/pgr_aStarCostMatrix.rst
- doc/bdAstar/pgr_bdAstar.rst
- doc/bdAstar/pgr_bdAstarCost.rst
- doc/bdAstar/pgr_bdAstarCostMatrix.rst
- doc/bdDijkstra/pgr_bdDijkstra.rst
- doc/bdDijkstra/pgr_bdDijkstraCost.rst
- doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
- doc/costMatrix/pgr_dijkstraCostMatrix.rst
- doc/dijkstra/pgr_dijkstra.rst
- doc/dijkstra/pgr_dijkstraCost.rst
- doc/driving_distance/pgr_drivingDistance.rst
- doc/ksp/pgr_KSP.rst
Fixes #1100
- Astar:
- bdAstar:
- Dijkstra:
- bdDijkstra:
> [WIP] fixing signatures on functions

- doc/costMatrix/pgr_withPointsCostMatrix.rst
- doc/mst/pgr_randomSpanTree.rst
- doc/withPoints/pgr_withPoints.rst
- doc/withPoints/pgr_withPointsCost.rst
- doc/withPoints/pgr_withPointsDD.rst
- doc/withPoints/pgr_withPointsKSP.rst
- doc/withPoints/pgr_withPointsVia.rst
Fixes #1100 
- Signatures and examples 
> doc-withPoints Fixed signatures and examples

- .travis.yml
- CMakeLists.txt
Sorry,
forgot to remove a flag that I was using for testing the workaround of the boost problem
This PR removes that flag
> [build] fixing a local change for testing

- doc/queries/doc-pgr_analyzeOneWay.queries
- doc/topology/pgr_analyzeOneWay.rst
- test/topology/doc-pgr_analyzeOneWay.result
- test/topology/doc-pgr_analyzeOneWay.test.sql
- test/topology/test.conf
Documenttion queries for pgr_analizeOneway are automatically generated
> pgr_analizeOneway documentation queries automatically generated

- doc/queries/CMakeLists.txt
- doc/queries/doc-pgr_nodeNetwork.queries
- doc/topology/pgr_nodeNetwork.rst
- test/topology/doc-pgr_nodeNetwork.result
- test/topology/doc-pgr_nodeNetwork.test.sql
- test/topology/test.conf
Fixing  errors in documentation queries 
> Pgr nodeNetwork

- pgtap/common/hasnt_v2_signatures.sql
Somehow the last PR merges created a typo on a test file
this PR fixes that
> [pgtap] fixing a typo

- NEWS
- doc/components/components-family.rst
- doc/components/pgr_articulationPoints.rst
- doc/components/pgr_biconnectedComponents.rst
- doc/components/pgr_bridges.rst
- doc/components/pgr_connectedComponents.rst
- doc/components/pgr_strongComponents.rst
- doc/src/proposed.rst
- doc/src/release_notes.rst
- doc/src/routingFunctions.rst
- sql/components/articulationPoints.sql
- sql/components/biconnectedComponents.sql
- sql/components/bridges.sql
- sql/components/connectedComponents.sql
- sql/components/strongComponents.sql
Making official the components family of function
> Official components

- sql/topology/createverticestable.sql
> Create vertices table

- sql/topology/nodeNetwork.sql
> Node network

- doc/ChPP/pgr_directedChPP.rst
- doc/ChPP/pgr_directedChPP_Cost.rst
- doc/allpairs/pgr_floydWarshall.rst
- doc/allpairs/pgr_johnson.rst
- doc/alpha_shape/pgr_alphaShape.rst
- doc/astar/pgr_aStar.rst
- doc/astar/pgr_aStarCost.rst
- doc/astar/pgr_aStarCostMatrix.rst
- doc/bdAstar/pgr_bdAstar.rst
- doc/bdAstar/pgr_bdAstarCost.rst
- doc/bdAstar/pgr_bdAstarCostMatrix.rst
- doc/bdDijkstra/pgr_bdDijkstra.rst
- doc/bdDijkstra/pgr_bdDijkstraCost.rst
- doc/bellman_ford/pgr_bellmanFord.rst
- doc/common/pgr_version.rst
- doc/components/pgr_articulationPoints.rst
- doc/components/pgr_biconnectedComponents.rst
- doc/components/pgr_bridges.rst
- doc/components/pgr_connectedComponents.rst
- doc/components/pgr_strongComponents.rst
- doc/contraction/pgr_contraction.rst
- doc/costFlow/pgr_minCostMaxFlow.rst
- doc/costFlow/pgr_minCostMaxFlow_Cost.rst
- doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
- doc/costMatrix/pgr_dijkstraCostMatrix.rst
- doc/costMatrix/pgr_withPointsCostMatrix.rst
- doc/dijkstra/pgr_dijkstraCost.rst
> Documentation links

- doc/src/proposed.rst
- doc/topologicalSort/pgr_topologicalSort.rst
- doc/transitiveClosure/pgr_transitiveClosure.rst
> [pgRouting] Change doc files.

- docqueries/version/doc-full_version.result
- src/pickDeliver/vehicle_pickDeliver.cpp
Fixes Delivers done before pickups.
> [pickDel] fix drop before pickup

- CMakeLists.txt
- doc/chinese/chinesePostmanProblem-family.rst
- doc/chinese/pgr_chinesePostman.rst
- doc/chinese/pgr_chinesePostmanCost.rst
- docqueries/version/doc-full_version.result
- docqueries/version/doc-version.result
- locale/.gitignore
- locale/en/LC_MESSAGES/chinesePostmanProblem-family.po
- locale/en/LC_MESSAGES/pgr_chinesePostman.po
- locale/en/LC_MESSAGES/pgr_chinesePostmanCost.po
- locale/pot/chinesePostmanProblem-family.pot
- locale/pot/pgr_chinesePostman.pot
- locale/pot/pgr_chinesePostmanCost.pot
- pumping up to v3.0.0-rc1
- adds a warning of possible server crash in experimental function `pgr_chinesePostman`
> Warning chinese

- ci/debbie/regress.sh
Upgrade to latest versions of these
Fixes # .
-
-
-
> Upgrade to debbie to newer versions of gdal, geos, postgis

- pgtap/topology/analyzeGraph/issue1311.sql
- sql/topology/analyzegraph.sql
Fixes #1311  .
- fix for 1311
- test of fix
> [topology] fix issue #1311

- locale/en/LC_MESSAGES/components-family.po
- locale/en/LC_MESSAGES/pgr_articulationPoints.po
- locale/en/LC_MESSAGES/pgr_biconnectedComponents.po
- locale/en/LC_MESSAGES/pgr_bridges.po
- locale/en/LC_MESSAGES/pgr_connectedComponents.po
- locale/en/LC_MESSAGES/pgr_strongComponents.po
- locale/en/LC_MESSAGES/pgr_trsp.po
- locale/pot/components-family.pot
- locale/pot/pgr_articulationPoints.pot
- locale/pot/pgr_biconnectedComponents.pot
- locale/pot/pgr_bridges.pot
- locale/pot/pgr_connectedComponents.pot
- locale/pot/pgr_strongComponents.pot
- locale/pot/pgr_trsp.pot
Fixes locale files with current contents of documentation
> [locale] updating files with typo fixes for translation

- doc/bdDijkstra/pgr_bdDijkstraCost.rst
Fixes #1325  .
Replaced with bdDijkstraCost where bdDijkstra was written
> Fix pgr_bdDijkstraCost documentation (#1325)

- doc/bdAstar/pgr_bdAstarCost.rst
Fixed the errors in Issue #1331 
> Fix pgr_bdAstarCost documentation (#1331)

- .editorconfig
- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- include/c_common/postgres_connection.h
- pgtap/alpha_shape/notebook-test.sql
- pgtap/astar/astar_ManyToMany-compare-dijkstra.test.sql
- pgtap/astar/astar_oneToMany-compare-dijkstra.test.sql
- pgtap/astar/astar_oneToOne-compare-dijkstra.test.sql
- pgtap/bdAstar/bdAstar-compare-dijkstra.sql
- pgtap/bdDijkstra/bdDijkstra-compare-dijkstra.sql
- pgtap/chinese/chinesePostman/innerQuery.sql
- pgtap/chinese/chinesePostmanCost/innerQuery.sql
- pgtap/contraction/combined/dijkstra-compare.sql
- pgtap/contraction/linear/undirected/dijkstra-compare.sql
- pgtap/dijkstra/oneToOne_equiv_manyToOne.test.sql
- pgtap/trsp/from1to3.test.sql
- pgtap/trsp/from3to4-directed.test.sql
- pgtap/withPoints/issue979DD.sql
- pgtap/withPoints/many_to_one_eq_one_to_one_withPoint.test.sql
- pgtap/withPoints/one_to_one_withPoint.test.sql
- pgtap/withPoints/undirected_equalityWPDijkstra.sql
- src/chinese/chinesePostman.c
- tools/developer/taptest.sh
- tools/testers/alphaShapeTester.sql
> Gh actions + close #1338

- doc/src/pgRouting-introduction.rst
- pgtap/topology/issue-1009.sql
- pgtap/topology/issue-1074.sql
- pgtap/topology/issue-1336.sql
- pgtap/topology/nodeNetwork.test.sql
- sql/topology/nodeNetwork.sql
Fixes #1336 , #1074 , #1009  .
- Fix `pgr_nodeNetwork()` function
- Add tests
> Fix pgr_nodeNetwork close #1336 #1074 #1009

- CMakeLists.txt
- docqueries/version/doc-full_version.result
- include/cpp_common/interruption.h
- include/dagShortestPath/pgr_dagShortestPath.hpp
- include/dijkstra/pgr_dijkstra.hpp
- src/common/basePath_SSEC.cpp
- src/dijkstra/dijkstra_driver.cpp
Compiling with visual studio is failing
This fixes PR fixes the build on  MS Visual Studio
* `std::numeric_limits<size_t>::max())` -> `(std::numeric_limits<size_t>::max)())`
* fixing some problems with pragmas in `interruptions.h`
> [build] fixes for visual studio

- .travis.yml
travis not to test code when only translations changes
> dont test code on PR of only translations

- .github/workflows/documentation.yml
- .github/workflows/linkcheck-es.yml
- .travis.yml
moving the link tests to github actions
> [actions] adding action to test links & removing test from travis

- .github/workflows/linkcheck-es.yml
- .travis.yml
Don't do any documentation task on `travis` as is done on `actions`
> [travis] Do nothing on travis when translations

- sql/sigs/CMakeLists.txt
v3.0.2 in CMakeLists to create the update script
> add missing v3.0.2

- .github/workflows/macos.yml
- .github/workflows/windows.yml
Sometimes the actions get canceled and currently they are not doing anything, so this are not going to be tested yet
Also removing spaces at end of lines of the edited files
> not testing macos action

- doc/conf.py.in
> [linkcheck] adding some configuration to link checking

- .github/workflows/check-files.yml
- .github/workflows/linkcheck-es.yml
Porting commit to master into develop
> [actions] test for signature files not changing on same minor (#1531)

- .github/workflows/ubuntu.yml
Fixes #1612 
Adds Postgres 13 to the build.
> adding postres 13

- .github/workflows/ubuntu.yml
> adding postres 13 to master Closes #1612

- NEWS
- doc/src/release_notes.rst
- Added `pgr_depthFirstSearch` and `pgr_sequentialVertexColoring` to the release notes.
- Updated the NEWS file
> Updated v3.2.0 release notes

- NEWS
- doc/src/release_notes.rst
- Added `pgr_isPlanar` and `pgr_makeConnected` to the release notes.
- Updated the NEWS file
> Modified release_notes.rst and NEWS

- doc/tsp/TSP-family.rst
- doc/tsp/pgr_TSP.rst
- doc/tsp/pgr_TSPeuclidean.rst
- pgtap/lineGraph/lineGraphFull/lineGraphFull_dijkstra_equivalence.sql
- pgtap/mincut/compare.test.sql
- pgtap/spanningTree/kruskal/kruskal/kruskal-edge-cases.sql
- pgtap/spanningTree/kruskal/kruskalBFS/kruskalBFS-edge-cases.sql
- pgtap/spanningTree/kruskal/kruskalDD/kruskalDD-edge-cases.sql
- pgtap/spanningTree/kruskal/kruskalDFS/kruskalDFS-edge-cases.sql
- pgtap/spanningTree/prim/prim/prim-edge-cases.sql
- pgtap/spanningTree/prim/primBFS/primBFS-edge-cases.sql
- pgtap/spanningTree/prim/primDD/primDD-edge-cases.sql
- pgtap/spanningTree/prim/primDFS/primDFS-edge-cases.sql
- src/dijkstra/dijkstraVia_driver.cpp
Fixes #1616 
- fix on dijkstraVia
> Fixing issue 1616 on dijkstra Via

- src/withPoints/withPoints_driver.cpp
Fixes #1616 
- fix on withPoints
> Fixing issue 1616 on withPoints

- pgtap/withPoints/issue1640.sql
- pgtap/withPoints/withPoints_oneToOne-compare-dijkstra.test.sql
- src/withPoints/withPoints_driver.cpp
> fix issue 1640 pgr_withPoints

- doc/src/pgRouting-concepts.rst
- locale/en/LC_MESSAGES/pgRouting-concepts.po
- locale/pot/pgRouting-concepts.pot
- Porting #1650
- Adding translation files
> Porting 1650

- NEWS
- doc/src/release_notes.rst
- include/contraction/pgr_contractionGraph.hpp
- locale/en/LC_MESSAGES/release_notes.po
- locale/pot/release_notes.pot
- pgtap/contraction/linear/directed/issue-1647.sql
- pgtap/contraction/linear/undirected/issue-1647.sql
Forward porting fix on 3.1 of 1647 from #1720 
- The fix
- The release notes on 3.1
> Issue 1647 dev

- include/chinese/pgr_chinesePostman.hpp
- include/max_flow/pgr_minCostMaxFlow.hpp
> [chinese] fixing server crash for 3.1

- include/chinese/pgr_chinesePostman.hpp
- include/max_flow/pgr_minCostMaxFlow.hpp
> [chinese] fixing server crash on develop

- pgtap/bdAstar/issue1733.sql
- src/bdAstar/bdAstar_driver.cpp
> Fix issue 1733 pgr_bdAstar

- pgtap/bdAstar/issue1733.sql
- src/bdAstar/bdAstar_driver.cpp
Ports #1734 fixes to 3.1.1 For #1733
> Fix issue 1733 for 3.0

- pgtap/bdAstar/issue1733.sql
- src/bdAstar/bdAstar_driver.cpp
Ports #1734 fixes to 3.1.1 For  #1733 
> Fix issue 1733 for 3.1

- pgtap/withPoints/issue1640.sql
- pgtap/withPoints/withPoints_oneToOne-compare-dijkstra.test.sql
- src/withPoints/withPoints_driver.cpp
* [withPoints] Added pgtap tests to compare with dijkstra
* [withPoints] Created pgTAP tests for issue1640
* [withPoints] Fixed the issue
Fixes #1640 on 3.1.1 porting fix from #1641 
> Fix issue 1640 pgr_withPoints (#1641)

- NEWS
- doc/src/release_notes.rst
- Update NEWS and release_notes with issue 1640 and issue 1733
> Update release notes for 3.0.3

- NEWS
- doc/src/release_notes.rst
- Update pgRouting 3.0.3 and 3.1.1 release notes
> Update release notes for 3.1

- NEWS
- doc/src/release_notes.rst
- Update pgRouting 3.0.3 and 3.1.1 release notes
> Update release notes for 3.2 dev

- CMakeLists.txt
- NEWS
- doc/src/release_notes.rst
- docqueries/version/doc-full_version.result
- docqueries/version/doc-version.result
> [build] pumping up version to 3.1.2

- CMakeLists.txt
- NEWS
- doc/src/release_notes.rst
- docqueries/version/doc-full_version.result
- docqueries/version/doc-version.result
> [build] pump up to version 3.0.4

- NEWS
- doc/src/release_notes.rst
- docqueries/version/doc-full_version.result
- tools/testers/pg_prove_tests.sh
> [build] fixing 1356 on 3.0

- NEWS
- doc/src/release_notes.rst
- docqueries/version/doc-full_version.result
- tools/testers/pg_prove_tests.sh
> [build] fixing #1356 on 3.1

- NEWS
- doc/src/release_notes.rst
- docqueries/version/doc-full_version.result
- pgtap/tsp/issues/issue-1760.sql
- src/cpp_common/Dmatrix.cpp
- src/tsp/euclideanDmatrix.cpp
> Fix Issue 1760 on 3.1

- NEWS
- doc/src/release_notes.rst
- docqueries/pickDeliver/design_pgtap.result
- docqueries/pickDeliver/doc-pickDeliver.result
- docqueries/pickDeliver/doc-pickDeliver.test.sql
- docqueries/version/doc-full_version.result
- include/cpp_common/Dmatrix.h
- include/vrp/dnode.h
- include/vrp/fleet.h
- include/vrp/pd_orders.h
- include/vrp/pgr_pickDeliver.h
- include/vrp/tw_node.h
- include/vrp/vehicle.h
- include/vrp/vehicle_node.h
- include/vrp/vehicle_pickDeliver.h
- pgtap/alpha_shape/notebook-test.sql
- pgtap/pickDeliver/pickDeliver/innerQuery.sql
- pgtap/pickDeliver/pickDeliver/issue-1725.sql
- pgtap/pickDeliver/pickDeliver/many-calls.sql
- src/cpp_common/Dmatrix.cpp
- src/pickDeliver/CMakeLists.txt
- src/pickDeliver/dnode.cpp
- src/pickDeliver/fleet.cpp
- src/pickDeliver/pd_orders.cpp
- src/pickDeliver/pgr_pickDeliver.cpp
- src/pickDeliver/pickDeliverEuclidean_driver.cpp
- src/pickDeliver/pickDeliver_driver.cpp
- src/pickDeliver/tw_node.cpp
- src/pickDeliver/vehicle_pickDeliver.cpp
Backporting commits from #1782 
> Fixes server crash on pgr_pickDeliver & pgr_vrpOneDepot for 3.0

- NEWS
- doc/src/release_notes.rst
- docqueries/pickDeliver/design_pgtap.result
- docqueries/pickDeliver/doc-pickDeliver.result
- docqueries/pickDeliver/doc-pickDeliver.test.sql
- docqueries/version/doc-full_version.result
- include/cpp_common/Dmatrix.h
- include/vrp/dnode.h
- include/vrp/fleet.h
- include/vrp/pd_orders.h
- include/vrp/pgr_pickDeliver.h
- include/vrp/tw_node.h
- include/vrp/vehicle.h
- include/vrp/vehicle_node.h
- include/vrp/vehicle_pickDeliver.h
- pgtap/alpha_shape/notebook-test.sql
- pgtap/pickDeliver/pickDeliver/innerQuery.sql
- pgtap/pickDeliver/pickDeliver/issue-1725.sql
- pgtap/pickDeliver/pickDeliver/many-calls.sql
- src/cpp_common/Dmatrix.cpp
- src/pickDeliver/CMakeLists.txt
- src/pickDeliver/dnode.cpp
- src/pickDeliver/fleet.cpp
- src/pickDeliver/pd_orders.cpp
- src/pickDeliver/pgr_pickDeliver.cpp
- src/pickDeliver/pickDeliverEuclidean_driver.cpp
- src/pickDeliver/pickDeliver_driver.cpp
- src/pickDeliver/tw_node.cpp
- src/pickDeliver/vehicle_pickDeliver.cpp
Fixes #1725 & #1304 
@landryb
Changes for the last test you made: Cleaned up the PR so to have the minimal changes to fix the issue
As we do not have a CI for openbsd, can you test this PR, and give us a report, Just to make sure I did not miss a needed change.
Thanks
I also added a link fix to pgr_alphaShape pgtap test, so on the porting that will be fixed also
On the meantime as the C/C++ code is the same on 3.0 & on 3.2 on develop branch I will be porting this commits to those versions.
> Fixes server crash on pgr_pickDeliver & pgr_vrpOneDepot

- include/vrp/book_keeping.h
- include/vrp/fleet.h
- include/vrp/pd_orders.h
- include/vrp/pgr_pickDeliver.h
- src/pickDeliver/dnode.cpp
- src/pickDeliver/fleet.cpp
- src/pickDeliver/initial_solution.cpp
- src/pickDeliver/optimize.cpp
- src/pickDeliver/pd_orders.cpp
- src/pickDeliver/pgr_pickDeliver.cpp
- src/pickDeliver/pickDeliver_driver.cpp
- src/pickDeliver/tw_node.cpp
- src/pickDeliver/vehicle.cpp
- Removed the `#if 0` code.
- Removed some `TODO`.
> Cleaned pgr_pickDeliver code

- doc/conf.py.in
> Added broken link to linkcheck_ignore on 3.1

- doc/conf.py.in
> Added broken link to linkcheck_ignore on 3.2

- .github/workflows/macos.yml
Ports #1840 changes to version 3.0
> Support macOS on CI (#1840)

- README.md
- doc/src/pgRouting-introduction.rst
- Changed license to GPL-2.0+
- Ports #1853 to 3.2
> Changed license to GPL-2.0+ on 3.2

- README.md
- doc/src/pgRouting-introduction.rst
- Changed license to GPL-2.0+
- Ports #1853 to 3.0
> Change license to GPL-2.0+ on 3.0

- CONTRIBUTING.md
- README.md
- doc/src/pgRouting-introduction.rst
Fixes #1851.
- Ports #1858 to 3.2
> Change license to GPL-2.0-or-later on 3.2

- NEWS
- doc/src/release_notes.rst
- docqueries/version/doc-full_version.result
- include/cpp_common/pgr_messages.h
- include/vrp/dnode.h
- include/vrp/fleet.h
- include/vrp/optimize.h
- include/vrp/pd_orders.h
- include/vrp/pd_problem.h
- include/vrp/pgr_pickDeliver.h
- include/vrp/solution.h
- include/vrp/vehicle.h
- src/cpp_common/pgr_messages.cpp
- src/pickDeliver/CMakeLists.txt
- src/pickDeliver/dnode.cpp
- src/pickDeliver/fleet.cpp
- src/pickDeliver/initial_solution.cpp
- src/pickDeliver/optimize.cpp
- src/pickDeliver/pd_orders.cpp
- src/pickDeliver/pd_problem.cpp
- src/pickDeliver/pgr_pickDeliver.cpp
- src/pickDeliver/solution.cpp
- src/pickDeliver/vehicle.cpp
> [pickDeliver] Removing singleton

- .github/workflows/release.yml
- NEWS
- doc/src/release_notes.rst
- requirements.txt
- tools/release-scripts/notes2news.pl
> Add GitHub Actions script for releases on 3.0

- README.md
> Corrected a typo in README.md file

- .github/workflows/publish-users-doc.yml
- Removed the line that deleted the spanish documentation. :(
> Fixed error during publishing documentation on 3.1

- .github/workflows/publish-users-doc.yml
> Fixed error during publishing documentation on 3.2

- include/c_common/arrays_input.h
- src/common/arrays_input.c
Fixes # .
-Developers documentation
-
-
> Fix #971 Developers documentation of array input file

- include/c_common/get_check_data.h
- include/c_types/column_info_t.h
- src/common/delauny_input.c
- src/common/get_check_data.c
- src/common/pgr_point_input.c
- src/common/points_input.c
Fixes #1894 
-  changes to column_info_t.h
-  adjusting code based on changes on structure Column_info_t
> fix for Issue1894 Column_info_t #1894 

- CONTRIBUTING.md
Fixes #1970 .
Enhanced Contributing.md 
> Fixes #1970

- src/alpha_shape/alphaShape.c
Fixes #1940
* changes to src/alpha_shape/alphaShape.c
> [alpha_shape] removing directive PGSQL_VERSION > 95 

- src/breadthFirstSearch/binaryBreadthFirstSearch.c
- src/breadthFirstSearch/breadthFirstSearch.c
> [breadthFirstSearch] removing directive PGSQL_VERSION > 95

- src/astar/astar.c
> [astar] removing directive PGSQL_VERSION > 95

- src/bdAstar/bdAstar.c
> [bdAstar] removing directive PGSQL_VERSION > 95

- src/max_flow/edge_disjoint_paths.c
- src/max_flow/max_flow.c
- src/max_flow/maximum_cardinality_matching.c
- src/max_flow/minCostMaxFlow.c
> [max_flow] removing directive PGSQL_VERSION > 95

- src/bellman_ford/bellman_ford.c
- src/bellman_ford/bellman_ford_neg.c
- src/bellman_ford/edwardMoore.c
> [bellman_ford] removing directive PGSQL_VERSION > 95

- include/c_types/pgr_components_rt.h
- include/drivers/components/biconnectedComponents_driver.h
- include/drivers/components/connectedComponents_driver.h
- include/drivers/components/strongComponents_driver.h
- src/components/biconnectedComponents.c
- src/components/connectedComponents.c
- src/components/strongComponents.c
Fixes #1908 .
- changes to pgr_components_rt.h
- adjusting code based on changes on structure pgr_components_rt
> fix for Issue1908 pgr_components_rt

- src/dijkstra/dijkstra.c
- src/dijkstra/dijkstraVia.c
> [dijkstra] removing directive PGSQL_VERSION > 95

- src/spanningTree/kruskal.c
- src/spanningTree/prim.c
- src/spanningTree/randomSpanningTree.c
> [spanningTree] removing directive PGSQL_VERSION > 95

- src/topologicalSort/topologicalSort.c
> [topologicalSort] removing directive PGSQL_VERSION > 95

- src/bdDijkstra/bdDijkstra.c
> [bdDijkstra] removing directive PGSQL_VERSION > 95

- src/chinese/chinesePostman.c
> [chinese] removing directive PGSQL_VERSION > 95

- src/tsp/TSP.c
- src/tsp/euclideanTSP.c
> [tsp] removing directive PGSQL_DIRECTIVE > 95

- src/traversal/depthFirstSearch.c
Fixes #1963 .
- changes to src/traversal/depthFirstSearch.c
> [traversal] removing directive PGSQL_VERSION > 95

- src/dagShortestPath/dagShortestPath.c
> [src/dagShortestPath] removing directive PGSQL_VERSION > 95

- include/c_common/delauny_input.h
- include/c_types/delauny_t.h
Fixes #1897 .
- changes to delauny_t.h
- adjusting code based on changes on structure Delauny_t 
> fix for Issue1897 Delauny_t 

- include/c_types/pgr_vertex_color_rt.h
- include/coloring/pgr_sequentialVertexColoring.hpp
- include/drivers/coloring/sequentialVertexColoring_driver.h
- src/coloring/sequentialVertexColoring.c
> fix for Issue1921 pgr_vertex_color_rt

- src/trsp/trsp.c
> [src/trsp] removing directive PGSQL_VERSION > 95

- src/coloring/bipartite.c
- src/coloring/sequentialVertexColoring.c
> [src/coloring] removing directive PGSQL_VERSION > 95

- src/mincut/stoerWagner.c
> [src/mincut] removing directive PGSQL_VERSION > 94

- src/withPoints/withPoints.c
> [src/withPoints] removing directive PGSQL_VERSION > 95

- src/contraction/contractGraph.c
> [src/contraction] removing directive PGSQL_VERSION > 95

- src/dominator/lengauerTarjanDominatorTree.c
> [src/dominator] removing directive PGSQL_VERSION > 95

- src/pickDeliver/pickDeliver.c
- src/pickDeliver/pickDeliverEuclidean.c
> [src/pickDeliver] removing directive PGSQL_VERSION > 95

- src/components/articulationPoints.c
- src/components/biconnectedComponents.c
- src/components/bridges.c
- src/components/connectedComponents.c
- src/components/makeConnected.c
- src/components/strongComponents.c
> [src/components] removing directive PGSQL_VERSION > 95

- src/driving_distance/many_to_dist_driving_distance.c
- src/driving_distance/many_to_dist_withPointsDD.c
> [src/driving_distance] removing directive PGSQL_VERSION > 95

- src/transitiveClosure/transitiveClosure.c
> [src/transitiveClosure] removing directive PGSQL_VERSION > 95

- include/allpairs/pgr_allpairs.hpp
- include/c_common/matrixRows_input.h
- include/c_types/matrix_cell_t.h
- include/cpp_common/Dmatrix.h
- include/drivers/allpairs/floydWarshall_driver.h
- include/drivers/allpairs/johnson_driver.h
- src/allpairs/floydWarshall.c
- src/allpairs/johnson.c
- src/common/matrixRows_input.c
- src/cpp_common/Dmatrix.cpp
Fixes #1903  .
- changes to matrix_cell_t.h
- adjusting code based on changes on structure `Matrix_cell_t`
> fix for Issue1903 Matrix_cell_t

- src/allpairs/floydWarshall.c
- src/allpairs/johnson.c
Fixes #1939 
This PR is the demonstration for OSD, do not merged until OSD ended
> [allpairs] removing directive PGSQL_VERSION > 95

- include/c_common/edges_input.h
- include/c_types/pgr_flow_t.h
- include/drivers/max_flow/max_flow_driver.h
- include/drivers/max_flow/minCostMaxFlow_driver.h
- src/common/edges_input.c
- src/max_flow/max_flow.c
- src/max_flow/minCostMaxFlow.c
> fix for 1912 adjustments for pgr_flow_t

- include/c_types/pgr_ltdtree_rt.h
- include/drivers/dominator/lengauerTarjanDominatorTree_driver.h
> fix for 1913 pgr_ltdtree_rt.h

- include/c_common/orders_input.h
- include/c_types/pickDeliver/pickDeliveryOrders_t.h
- src/common/orders_input.c
> fix 1923 pickDeliveryOrders_t.h

- include/c_types/line_graph_rt.h
- include/drivers/lineGraph/lineGraph_driver.h
- src/lineGraph/lineGraph.c
- src/lineGraph/lineGraph_driver.cpp
Fixes #1902 .
- changes to line_graph_rt.h
- adjusting code based on changes on structure Line_graph_rt
> fix for Issue1902 Line_graph_rt

- include/c_common/edges_input.h
- include/c_types/pgr_basic_edge_t.h
- src/common/edges_input.c
Fixes #1904 .
- changes to pgr_basic_edge_t.h
- adjusting code based on changes on structure pgr_basic_edge_t
> fix for Issue1904 pgr_basic_edge_t

- src/ksp/ksp.c
- src/ksp/turnRestrictedPath.c
- src/ksp/withPoints_ksp.c
> [src/ksp] removing directive PGSQL_VERSION > 95

- src/lineGraph/lineGraph.c
- src/lineGraph/lineGraphFull.c
> [src/lineGraph] removing directive PGSQL_VERSION > 95

- include/c_types/pgr_bipartite_rt.h
- include/coloring/pgr_bipartite_driver.hpp
- include/drivers/coloring/bipartite_driver.h
- src/coloring/bipartite.c
- src/coloring/bipartite_driver.cpp
Fixes #1905 .
- fixing pgr_bipartite_rt.h
- modifications due to the change on pgr_bipartite_rt
> Fixing Issue1905 pgr_bipartite_rt

- include/c_types/pgr_topologicalSort_t.h
- include/drivers/topologicalSort/topologicalSort_driver.h
- src/topologicalSort/topologicalSort.c
- src/topologicalSort/topologicalSort_driver.cpp
Fixes #1920  .
- fixing pgr_topologicalSort_t.h
- modifications due to the change on pgr_topologicalSort_t.h
> Fixing Issue1920 on pgr_topologicalSort_t

- include/c_types/pgr_boyer_t.h
Fixes #1906 .
- Changes to pgr_boyer_t.h
> fix for issue1906 pgr_boyer_t

- include/c_common/edges_input.h
- include/c_types/pgr_costFlow_t.h
- src/common/edges_input.c
Fixes #1909 .
- changes to pgr_costFlow_t.h
- adjusting code based on changes on structure pgr_costFlow_t
> fix for Issue1909 pgr_costFlow_t

- include/c_common/combinations_input.h
- include/c_types/pgr_combination_t.h
Fixes #1907 .
- changes to pgr_combination_t.h 
- adjusting code based on changes on structure pgr_combination_t
> fix for Issue1907 pgr_combination_t

- include/topologicalSort/pgr_topologicalSort.hpp
- src/chinese/chinesePostman.c
- src/components/strongComponents.c
- src/driving_distance/many_to_dist_withPointsDD.c
- src/topologicalSort/topologicalSort_driver.cpp
- tools/scripts/code_checker.sh
Some style errors were not catched.
PR fixes:
- action that checks the style
- fixes style errors
> Fix stylecheck

- include/c_common/vehicles_input.h
- include/c_types/pickDeliver/vehicle_t.h
- src/common/vehicles_input.c
Fixes pgRouting#1924
- changes to vehicle_t.h
- adjusting code based on changes on structure vehicle_t
> fix for Issue1924 Vehicle_t

- include/c_common/pgr_point_input.h
- include/c_types/pgr_point_t.h
- src/common/pgr_point_input.c
Fixes #1916 
-changes to pgr_point_t.h
-adjusting code based on changes on structure Pgr_point_t
> fixed issue1916 Pgr_point_t

- include/c_types/pgr_makeConnected_t.h
- include/components/pgr_makeConnected.hpp
- include/drivers/components/makeConnected_driver.h
- src/components/makeConnected.c
Fixes #1914 .
- changes to pgr_makeConnected_t.h
- adjusting code based on changes to structure pgr_makeConnected_t
> fix for Issue1914 pgr_makeConnected_t

- include/c_types/pgr_randomSpanningTree_t.h
- include/drivers/spanningTree/randomSpanningTree_driver.h
- src/spanningTree/randomSpanningTree.c
Fixes #1918 
-changes to pgr_randomSpanningTree_t.h
-adjusting code based on changes on structure pgr_randomSpanningTree_t
> fix for Issue1918 pgr_randomSpanningTree_t

- include/c_types/routes_t.h
- include/drivers/dijkstra/dijkstraVia_driver.h
- src/dijkstra/dijkstraVia.c
- src/dijkstra/dijkstraVia_driver.cpp
Fixes #1927  .
- Fixing routes_t.h
- adjustments due to the fix
> Issue1927 include/c_types/routes_t.h

- include/c_types/transitiveClosure_rt.h
- include/drivers/transitiveClosure/transitiveClosure_driver.h
- src/transitiveClosure/transitiveClosure.c
- src/transitiveClosure/transitiveClosure_driver.cpp
> Making compilation faster transitiveClosure_rt

- include/breadthFirstSearch/pgr_breadthFirstSearch.hpp
- include/c_types/mst_rt.h
- include/drivers/breadthFirstSearch/breadthFirstSearch_driver.h
- include/drivers/components/makeConnected_driver.h
- include/drivers/planar/boyerMyrvold_driver.h
- include/drivers/planar/isPlanar_driver.h
- include/drivers/spanningTree/kruskal_driver.h
- include/drivers/spanningTree/prim_driver.h
- include/drivers/traversal/depthFirstSearch_driver.h
- include/spanningTree/details.hpp
- include/spanningTree/pgr_kruskal.hpp
- include/spanningTree/pgr_mst.hpp
- include/spanningTree/pgr_prim.hpp
- include/traversal/pgr_depthFirstSearch.hpp
- src/breadthFirstSearch/breadthFirstSearch.c
- src/breadthFirstSearch/breadthFirstSearch_driver.cpp
- src/spanningTree/details.cpp
- src/spanningTree/kruskal.c
- src/spanningTree/kruskal_driver.cpp
- src/spanningTree/prim.c
- src/spanningTree/prim_driver.cpp
- src/traversal/depthFirstSearch.c
- src/traversal/depthFirstSearch_driver.cpp
Fixes #1915 .
- pgr_mst_rt -> MST_rt
> Making compilation faster mst_rt.h

- include/c_common/restrictions_input.h
- include/c_types/restriction_t.h
- include/cpp_common/rule.h
- include/drivers/trsp/trsp_driver.h
- include/drivers/yen/turnRestrictedPath_driver.h
- src/common/restrictions_input.c
- src/cpp_common/rule.cpp
- src/ksp/turnRestrictedPath_driver.cpp
- src/trsp/trsp_driver.cpp
> Making compilation faster include/c_types/restriction_t.h

- include/c_common/points_input.h
- include/c_types/point_on_edge_t.h
- include/drivers/driving_distance/withPoints_dd_driver.h
- include/drivers/withPoints/withPoints_driver.h
- include/drivers/yen/withPoints_ksp_driver.h
- src/common/points_input.c
- src/withPoints/withPoints.c
> Making compilation faster include/c_types/point_on_edge_t.h

- include/c_types/stoerWagner_t.h
- include/drivers/mincut/stoerWagner_driver.h
- include/mincut/pgr_stoerWagner.hpp
- src/mincut/stoerWagner.c
- src/mincut/stoerWagner_driver.cpp
> Making compilation faster pgr stoer wagner t

- include/c_common/edges_input.h
- include/c_types/pgr_edge_xy_t.h
- src/common/edges_input.c
> Making compilation faster, chaging pgr_edge_xy_t.h

- NEWS
- doc/conf.py.in
- doc/src/pgRouting-introduction.rst
- doc/src/release_notes.rst
- Removed the links from `linkcheck_ignore`
- Added name in the contributor's list.
- Updated release notes and NEWS.
> Edge coloring doc

- include/c_types/geom_text_rt.h
- include/drivers/alpha_shape/alphaShape_driver.h
- src/alpha_shape/alphaShape_driver.cpp
Fixes #1899 
- Made Compilation faster for geom_text_rt.h
- Fixed geom_text_rt.h and made changes in alphaShape_driver.h & alphaShape_driver.cpp
-
> Fixed Issue1899 for  geom_text_rt.h

- docqueries/contraction/doc-contraction-family.result
- docqueries/contraction/doc-contraction-family.test.sql
- docqueries/contraction/doc-pgr_contraction.result
- docqueries/contraction/doc-pgr_contraction.test.sql
Fixes #2133 .
- changed the sql and result files to change --q* to \* q* \*
> [contraction] fixing PLSQL

- docqueries/alpha_shape/doc-pgr_alphashape.result
- docqueries/alpha_shape/doc-pgr_alphashape.test.sql
Fixes #2122 
- changed the sql and result files to fix the codacy PLSQL errors/warnings
> [alpha_shape] fixing PLSQL

- docqueries/breadthFirstSearch/doc-pgr_binaryBreadthFirstSearch.result
- docqueries/breadthFirstSearch/doc-pgr_binaryBreadthFirstSearch.test.sql
- docqueries/breadthFirstSearch/doc-pgr_breadthFirstSearch.result
- docqueries/breadthFirstSearch/doc-pgr_breadthFirstSearch.test.sql
> [breadthFirstSearch] Fixing PSQL

- docqueries/astar/doc-aStarCost.result
- docqueries/astar/doc-aStarCost.test.sql
- docqueries/astar/doc-aStarCostMatrix.result
- docqueries/astar/doc-aStarCostMatrix.test.sql
- docqueries/astar/doc-astar.result
- docqueries/astar/doc-astar.test.sql
> [astar] fixing PLSQL

- docqueries/driving_distance/doc-pgr_drivingDistance.result
- docqueries/driving_distance/doc-pgr_drivingDistance.test.sql
> [driving_distance] fixing PLSQL

- docqueries/mincut/doc-stoerWagner.result
- docqueries/mincut/doc-stoerWagner.test.sql
> [mincut] fixing PLSQL

- docqueries/components/doc-pgr_articulationPoints.result
- docqueries/components/doc-pgr_articulationPoints.test.sql
- docqueries/components/doc-pgr_biconnectedComponents.result
- docqueries/components/doc-pgr_biconnectedComponents.test.sql
- docqueries/components/doc-pgr_bridges.result
- docqueries/components/doc-pgr_bridges.test.sql
- docqueries/components/doc-pgr_connectedComponents.result
- docqueries/components/doc-pgr_connectedComponents.test.sql
- docqueries/components/doc-pgr_makeConnected.result
- docqueries/components/doc-pgr_makeConnected.test.sql
- docqueries/components/doc-pgr_strongComponents.result
- docqueries/components/doc-pgr_strongComponents.test.sql
> [components] fixing PLSQL

- docqueries/max_flow/doc-pgr_boykovKolmogorov.result
- docqueries/max_flow/doc-pgr_boykovKolmogorov.test.sql
- docqueries/max_flow/doc-pgr_edgeDisjointPaths.result
- docqueries/max_flow/doc-pgr_edgeDisjointPaths.test.sql
- docqueries/max_flow/doc-pgr_edmondsKarp.result
- docqueries/max_flow/doc-pgr_edmondsKarp.test.sql
- docqueries/max_flow/doc-pgr_maxCardinalityMatch.result
- docqueries/max_flow/doc-pgr_maxCardinalityMatch.test.sql
- docqueries/max_flow/doc-pgr_maxFlow.result
- docqueries/max_flow/doc-pgr_maxFlow.test.sql
- docqueries/max_flow/doc-pgr_maxFlowMinCost.result
- docqueries/max_flow/doc-pgr_maxFlowMinCost.test.sql
- docqueries/max_flow/doc-pgr_maxFlowMinCost_Cost.result
- docqueries/max_flow/doc-pgr_maxFlowMinCost_Cost.test.sql
- docqueries/max_flow/doc-pgr_pushRelabel.result
- docqueries/max_flow/doc-pgr_pushRelabel.test.sql
Fixes #2140 .
- change comments to C style
> [max_flow] fixing PLSQL

- docqueries/dominator/doc-lengauerTarjanDominatorTree.result
- docqueries/dominator/doc-lengauerTarjanDominatorTree.test.sql
Fixes #2136 
- Changing comments to C style
> [dominator] fixing PLSQL

- docqueries/dijkstra/doc-pgr_dijkstra.result
- docqueries/dijkstra/doc-pgr_dijkstra.test.sql
- docqueries/dijkstra/doc-pgr_dijkstraCost.result
- docqueries/dijkstra/doc-pgr_dijkstraCost.test.sql
- docqueries/dijkstra/doc-pgr_dijkstraCostMatrix.result
- docqueries/dijkstra/doc-pgr_dijkstraCostMatrix.test.sql
- docqueries/dijkstra/doc-pgr_dijkstraNear.result
- docqueries/dijkstra/doc-pgr_dijkstraNear.test.sql
- docqueries/dijkstra/doc-pgr_dijkstraNearCost.result
- docqueries/dijkstra/doc-pgr_dijkstraNearCost.test.sql
- docqueries/dijkstra/doc-pgr_dijkstraVia.result
- docqueries/dijkstra/doc-pgr_dijkstraVia.test.sql
> [Dijkstra] fixing PLSQL #2135

- docqueries/ksp/doc-ksp.result
- docqueries/ksp/doc-ksp.test.sql
- docqueries/ksp/doc-pgr_turnRestrictedPath.result
- docqueries/ksp/doc-pgr_turnRestrictedPath.test.sql
> [ksp] fixing PLSQL

- docqueries/chinese/doc-pgr_chinesePostman.result
- docqueries/chinese/doc-pgr_chinesePostman.test.sql
- docqueries/chinese/doc-pgr_chinesePostmanCost.result
- docqueries/chinese/doc-pgr_chinesePostmanCost.test.sql
> [chinese] fixing PLSQL

- docqueries/bdAstar/doc-pgr_bdAstar.result
- docqueries/bdAstar/doc-pgr_bdAstar.test.sql
- docqueries/bdAstar/doc-pgr_bdAstarCost.result
- docqueries/bdAstar/doc-pgr_bdAstarCost.test.sql
- docqueries/bdAstar/doc-pgr_bdAstarCostMatrix.result
- docqueries/bdAstar/doc-pgr_bdAstarCostMatrix.test.sql
Fixes [#2125](https://github.com/pgRouting/pgrouting/issues/2125).
- Updated .SQL and .result files in DocQueries/bdAstar.
> [bdAstar] fixing PLSQL Issue# 2125

- docqueries/allpairs/doc-floydWarshall.test.sql
- docqueries/allpairs/doc-johnson.test.sql
> [allpairs] fixing PLSQL

- doc/version/pgr_version.rst
> [doc] pgr_version.rst Corrected typo

- doc/astar/pgr_aStar.rst
- doc/astar/pgr_aStarCost.rst
- doc/dijkstra/pgr_dijkstraCost.rst
- doc/dijkstra/pgr_dijkstraVia.rst
- doc/src/pgRouting-introduction.rst
- docqueries/allpairs/doc-floydWarshall.result
- docqueries/allpairs/doc-johnson.result
- docqueries/breadthFirstSearch/doc-pgr_binaryBreadthFirstSearch.result
- docqueries/contraction/doc-pgr_contraction.result
- docqueries/dominator/doc-lengauerTarjanDominatorTree.result
- docqueries/ksp/doc-ksp.result
Fixes some documentation issues that arouse from some older commits
> Fix documentation references to results

- include/drivers/tsp/TSP_driver.h
Fixes #2118 
- Updating code to use using keyword for C++ and typedef otherwise.
> [tsp] adjusting drivers

- include/drivers/withPoints/withPoints_driver.h
Fixes #2119
- Used keyword using instead of typedef for C++
> [withPoints] adjusting drivers

- docqueries/dagShortestPath/doc-pgr_dagShortestPath.result
- docqueries/dagShortestPath/doc-pgr_dagShortestPath.test.sql
Fixes #2134 
- Changing comments to C style.
> [dagShortestPath] fixing PLSQL

- docqueries/coloring/doc-bipartite.result
- docqueries/coloring/doc-bipartite.test.sql
- docqueries/coloring/doc-edgeColoring.result
- docqueries/coloring/doc-edgeColoring.test.sql
- docqueries/coloring/doc-pgr_sequentialVertexColoring.result
- docqueries/coloring/doc-pgr_sequentialVertexColoring.test.sql
Fixes #2130 
- Changing comments to C style
> [coloring] fixing PLSQL

- .github/workflows/ubuntu.yml
- NEWS
- doc/dijkstra/dijkstra-family.rst
- doc/dijkstra/pgr_dijkstraNear.rst
- doc/dijkstra/pgr_dijkstraNearCost.rst
- doc/src/experimental.rst
- doc/src/release_notes.rst
- sql/dijkstra/_dijkstraNear.sql
- sql/dijkstra/dijkstraNear.sql
- sql/dijkstra/dijkstraNearCost.sql
- tools/testers/setup_db.sh
Fixes #2203 
- SQL files comments marked as proposed
- Documentation files Experimental -> proposed
- Updated NEWS and release notes
Additionally
- Added postgreSQL 14 to the `Build For ubuntu`  action
-  PostGIS 2.5 is not released for postgreSQL 14, so that combination is not tested
> Issue 2203 pg dijkstra near to proposed

- NEWS
- doc/coloring/coloring-family.rst
- doc/coloring/pgr_sequentialVertexColoring.rst
- doc/src/proposed.rst
- doc/src/release_notes.rst
- sql/coloring/bipartite.sql
- sql/coloring/edgeColoring.sql
- sql/coloring/sequentialVertexColoring.sql
Fixes #2202 .
-    SQL files comments marked as proposed
-    SQL files comments marked as experimental on other coloring functions
-    Documentation files Experimental -> proposed
-    Updated NEWS and release notes
> [pgr_sequentialVertexColoring] promoted to proposed

- NEWS
- doc/allpairs/pgr_johnson.rst
- doc/bdDijkstra/pgr_bdDijkstra.rst
- doc/max_flow/flow-family.rst
- doc/src/pgRouting-introduction.rst
- doc/src/release_notes.rst
- doc/traversal/traversal-family.rst
- doc/withPoints/pgr_withPointsCost.rst
> [doc] fix some mistakes

- include/drivers/coloring/edgeColoring_driver.h
- pgtap/coloring/edgeColoring/edge_cases.pg
- src/coloring/edgeColoring.c
- Fixing **include/drivers/coloring/edgeColoring_driver.h** https://github.com/pgRouting/pgrouting/blob/main/include/drivers/coloring/edgeColoring_driver.h#L2
- Fixing **pgtap/coloring/edgeColoring/edge-cases.sql**
- Fixing **src/coloring/edgeColoring.c** https://github.com/pgRouting/pgrouting/blob/main/src/coloring/edgeColoring.c#L160
> [pgr_edgeColoring] Fixing some bugs

- pgtap/dijkstra/dijkstra/edge_cases/zero_one_edge_no_reverse.pg
- tools/testers/dijkstra_pgtap_tests.sql
> [dijkstra][pgtap] simplification of tests

- pgtap/bdDijkstra/bdDijkstra/types_check.pg
- pgtap/dijkstra/dijkstra/edge_cases/zero_one_edge_no_reverse.pg
- pgtap/dijkstra/dijkstra/types_check.pg
- tools/testers/dijkstra_pgtap_tests.sql
Added missing conditionals for testing with old 3.x versions
https://github.com/cvvergara/pgrouting/actions/runs/1646444884
> [pgtap] fixing some issues with testing old 3.x version

- doc/conf.py.in
- doc/src/CMakeLists.txt
- doc/src/pgRouting-concepts.rst
- doc/src/proposed.rst
- doc/src/via-category.rst
- doc/src/withPoints-category.rst
- doc/trsp/TRSP-family.rst
- doc/trsp/pgr_trspVia_withPoints.rst
- doc/trsp/pgr_trsp_withPoints.rst
- doc/withPoints/pgr_withPoints.rst
- doc/withPoints/pgr_withPointsCost.rst
- doc/withPoints/pgr_withPointsCostMatrix.rst
- doc/withPoints/pgr_withPointsDD.rst
- doc/withPoints/pgr_withPointsKSP.rst
- doc/withPoints/pgr_withPointsVia.rst
- doc/withPoints/withPoints-family.rst
- docqueries/src/CMakeLists.txt
- docqueries/src/test.conf
- docqueries/src/withPoints-category.result
- docqueries/src/withPoints-category.test.sql
- docqueries/trsp/trspVia_withPoints.result
- docqueries/trsp/trspVia_withPoints.test.sql
Refines documentation 
related issue: #2238 
> Refine trsp with points documentation

- doc/bellman_ford/pgr_bellmanFord.rst
- doc/bellman_ford/pgr_edwardMoore.rst
- docqueries/bellman_ford/doc-pgr_bellmanFord.result
- docqueries/bellman_ford/doc-pgr_bellmanFord.test.sql
- docqueries/bellman_ford/doc-pgr_edwardMoore.result
- docqueries/bellman_ford/doc-pgr_edwardMoore.test.sql
Fixes #2244 .
- doc/bellman_ford/pgr_bellmanFord.rst  
- doc/bellman_ford/pgr_edwardMoore.rst
This is my first pr. Please suggest if anything is incorrect.
> bellmanford doc refinement and change of code-block to parsed-literal

- docqueries/bellman_ford/doc-pgr_bellmanFord.result
- docqueries/bellman_ford/doc-pgr_edwardMoore.result
Fixes docqueries of Bellman ford functions
> [bellman_ford] fixing docqueries results

- doc/coloring/coloring-family.rst
- doc/coloring/pgr_bipartite.rst
- doc/coloring/pgr_edgeColoring.rst
- doc/coloring/pgr_sequentialVertexColoring.rst
Fixes #2244.
- Minor docs refinement for coloring-family
- Changed code-block to parsed-literal.
- Adjusted proper doc alignments.
> coloring-family doc refinement

- doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
- doc/breadthFirstSearch/pgr_breadthFirstSearch.rst
- docqueries/breadthFirstSearch/doc-pgr_binaryBreadthFirstSearch.result
- docqueries/breadthFirstSearch/doc-pgr_binaryBreadthFirstSearch.test.sql
- docqueries/breadthFirstSearch/doc-pgr_breadthFirstSearch.result
- docqueries/breadthFirstSearch/doc-pgr_breadthFirstSearch.test.sql
Fixes #2244 .
- doc/breadthFirstSearch/pgr_breadthFirstSearch.rst
- doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
> Breadth first search parsed literal

- doc/src/index.rst
- doc/src/routingFunctions.rst
- doc/version/CMakeLists.txt
- doc/version/pgr_full_version.rst
- doc/version/pgr_version.rst
- doc/version/reference.rst
Fixes #2244 .
- refinement of reference functions
> [version] refinement of documentation

- doc/conf.py.in
- doc/tsp/TSP-family.rst
- doc/tsp/pgr_TSP.rst
- doc/tsp/pgr_TSPeuclidean.rst
- doc/version/pgr_full_version.rst
- doc/version/pgr_version.rst
- doc/version/reference.rst
- src/common/coordinates_input.c
- src/common/matrixRows_input.c
Fixes #2244 .
- TSP using parsed literal and documentation refinement
> Tsp parsed literal

- doc/astar/pgr_aStar.rst
- doc/bdAstar/pgr_bdAstar.rst
- doc/bdDijkstra/pgr_bdDijkstra.rst
- doc/bellman_ford/pgr_bellmanFord.rst
- doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
- doc/dijkstra/pgr_dijkstra.rst
- doc/max_flow/pgr_edgeDisjointPaths.rst
- doc/spanningTree/pgr_kruskal.rst
- doc/spanningTree/pgr_kruskalBFS.rst
- doc/spanningTree/pgr_kruskalDD.rst
- doc/spanningTree/pgr_kruskalDFS.rst
- doc/src/pgRouting-concepts.rst
- doc/traversal/BFS-category.rst
- doc/trsp/pgr_trsp.rst
Fixes some inconsistencies found using weblate for translation
> [doc] fixing inconsistencies

- doc/src/pgRouting-installation.rst
Fixes #1866.
- Developed the issue on the main branch and cherry-picked it to develop branch. 
- Provided more clarification on configuring PostgreSQL as per the request in the issue.
- Updated component installation instructions as per requirements.
- Fixed the grammatical issues in the instructions and provided more clarifications as per the requirements.
- Fixed doc alignments.
> improving pgrouting installation page

- doc/conf.py.in
- regex for link ignore needed for other languages
> [links] link ignore needed for other languages

- locale/es/LC_MESSAGES/index.po
- locale/es/LC_MESSAGES/pgr_degree.po
- locale/zh_Hans/LC_MESSAGES/index.po
- locale/zh_Hans/LC_MESSAGES/pgr_degree.po
Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [pgRouting/index](https://weblate.osgeo.org/projects/pgrouting/index/).
It also includes following components:
* [pgRouting/pgr_extractVertices](https://weblate.osgeo.org/projects/pgrouting/pgr_extractvertices/)
* [pgRouting/pgr_binaryBreadthFirstSearch](https://weblate.osgeo.org/projects/pgrouting/pgr_binarybreadthfirstsearch/)
* [pgRouting/pgr_isPlanar](https://weblate.osgeo.org/projects/pgrouting/pgr_isplanar/)
* [pgRouting/pgr_withPointsCost](https://weblate.osgeo.org/projects/pgrouting/pgr_withpointscost/)
* [pgRouting/pgr_dijkstraCost](https://weblate.osgeo.org/projects/pgrouting/pgr_dijkstracost/)
* [pgRouting/pgr_createTopology](https://weblate.osgeo.org/projects/pgrouting/pgr_createtopology/)
* …
> Translations update from OSGeo Weblate

- .github/dependabot.yml
- .github/workflows/boost_version.yml
- .github/workflows/check-files.yml
- .github/workflows/check-queries.yml
- .github/workflows/clang.yml
- .github/workflows/doc-check.yml
- .github/workflows/locale-and-website.yml
- .github/workflows/macos.yml
- .github/workflows/release.yml
- .github/workflows/ubuntu.yml
- .github/workflows/update.yml
- .github/workflows/windows.yml
Changes:
- Porting from #2303.
- Also including dependabot updates for actions from #2304, #2305, #2306
> chore(develop): Included githubactions in the dependabot config, and port Dependabot updates

- NEWS
- doc/src/pgRouting-introduction.rst
- doc/src/release_notes.rst
- pgtap/topology/extractVertices/edge-cases.sql
- sql/topology/extractVertices.sql
Fixes #2312 .
- pgtap test
- fix
- documentation about the fix
- And update about a sponsor
Reminder:
Do not release 3.2 until the work on the documentation on develop is finished.
> Extract vertices issue

- doc/src/via-category.rst
- doc/trsp/pgr_turnRestrictedPath.rst
Fixes problem detected when translating.
> [doc] fixing problem catched with translation

- .github/workflows/update.yml
- doc/topology/pgr_analyzeOneWay.rst
- doc/trsp/pgr_turnRestrictedPath.rst
- doc/version/pgr_version.rst
- doc/withPoints/pgr_withPointsCost.rst
- include/c_common/get_check_data.h
- pgtap/contraction/linear/directed/issue_1647.pg
- pgtap/contraction/linear/undirected/issue_1647.pg
- pgtap/max_flow/maxCardinalityMatch/inner_query.pg
- pgtap/max_flow/maxCardinalityMatch/no_crash_test.pg
- pgtap/withPoints/withPoints/edge_cases/issue_1640.pg
- pgtap/withPoints/withPoints/edge_cases/issue_2254.pg
- sql/common/_checkcolumn.sql
- src/common/get_check_data.c
- tools/testers/innerQuery.sql
work on #2369 
- adjust update test 
- adjusted some messages & fix some pgtap tests
- doc fix typos
> Release tasks 6

- doc/conf.py.in
Ignoring a link that is causing a fail
> [conf] ingnoring link latest/pgr

- CMakeLists.txt
- src/trsp/trsp.c
> Fix for centos build #2415 for pgRouting develop 3.5.0

- doc/src/pgRouting-installation.rst
Fixes # .
-Installation part in  documententation has been modified
-PostgresQL 14 is changed to PostgresQL 15
> postgres 14 ->15

- CMakeLists.txt
- docqueries/version/doc-full_version.result
- docqueries/version/doc-version.result
Preparation before moving to main
> Version adjustment before moving to main

- .github/workflows/centos.yml
> [CI] fixing centos test

- .github/workflows/centos.yml
> Ci centos fix dev t1

- docqueries/common/versionless-any-01.result
- docqueries/common/versionless-any-01.test.sql
- docqueries/ordering/cuthillMckeeOrdering.result
- docqueries/ordering/cuthillMckeeOrdering.test.sql
- docqueries/src/concepts.result
- docqueries/src/concepts.test.sql
- docqueries/src/sampledata.result
- docqueries/topology/doc-pgr_analyzeGraph.result
- docqueries/topology/doc-pgr_analyzeGraph.test.sql
- docqueries/topology/doc-pgr_analyzeOneWay.result
- docqueries/topology/doc-pgr_analyzeOneWay.test.sql
- docqueries/topology/doc-pgr_createTopology.result
- docqueries/topology/doc-pgr_createTopology.test.sql
- docqueries/trsp/issue704.result
- docqueries/trsp/issue704.test.sql
- docqueries/trsp/issue717.result
- docqueries/trsp/issue717.test.sql
- docqueries/trsp/trsp-any-02.result
- docqueries/trsp/trsp-any-02.test.sql
- docqueries/trsp/trsp_vias-any-04.result
- docqueries/trsp/trsp_vias-any-04.test.sql
- docqueries/tsp/doc-pgr_TSPeuclidean.result
- docqueries/tsp/doc-pgr_TSPeuclidean.test.sql
- docqueries/utilities/findCloseEdges.result
- docqueries/utilities/findCloseEdges.test.sql
- pgtap/dijkstra/dijkstra/edge_cases/oneToOne_equiv_manyToMany.pg
- pgtap/dijkstra/dijkstra/edge_cases/oneToOne_equiv_manyToOne.pg
- tools/testers/sampledata.sql
- (re-)fixing the space issue on some pgtap tests
- moving `-- comments` to `/* comments */` on pgtap tests
> Prerelease issue fix

- src/allpairs/floydWarshall.c
- src/allpairs/johnson.c
- src/coloring/sequentialVertexColoring.c
Fixes #2476  
- free -> pfree
- fixing a size issue on coloring
> Issue 2476 fix allpairs

- include/cpp_common/interruption.h
Roll back changes on interrupts include file
> [interrupt] restoring original file

- include/cpp_common/interruption.h
> Fix mingw64 compile (develop)

- .github/workflows/ubuntu.yml
Fixes # .
-added postgres 15 as dependency
-
-
> added postgres 15 as dependency

- locale/es/LC_MESSAGES/pgrouting_doc_strings.po
- locale/ja/LC_MESSAGES/pgrouting_doc_strings.po
- locale/ko/LC_MESSAGES/pgrouting_doc_strings.po
- locale/pot/pgrouting_doc_strings.pot
Fixes end-of-line within string on line from weblate
> [locale] fix error on locale files

- doc/_static/page_history.js
- include/cpp_common/basePath_SSEC.hpp
- include/cpp_common/identifier.h
- include/cpp_common/identifiers.hpp
- include/cpp_common/xy_vertex.h
- include/vrp/order.h
- include/vrp/pd_orders.h
- include/vrp/tw_node.h
- include/vrp/vehicle.h
- include/vrp/vehicle_node.h
- include/vrp/vehicle_pickDeliver.h
- Remove clang warnings
- Updates the page_history with the fixed values on the PR to the gh-pages
> Fix clang warnings

- ci/winnie/build_pgrouting.sh
- ci/winnie/package_pgrouting.sh
- tools/scripts/test_shell.sh
* Fix winnie build and test.  Closes #2513
* Exclude checking winnie's build script from shell checking
* Didn't exclude right test
Fixes # 2513
-
-
-
> Fix winnie build (#2514) - develop branch

- .github/workflows/centos.yml
- .github/workflows/update-locale.yml
Locale can not be updated because of branch protection
> Not updating locale on main

- .github/workflows/update-locale.yml
- NEWS
- doc/dijkstra/pgr_dijkstra.rst
- doc/src/release_notes.rst
- doc/topology/pgr_degree.rst
- doc/topology/topology-functions.rst
- docqueries/topology/degree.result
- docqueries/topology/degree.test.sql
- locale/en/LC_MESSAGES/pgrouting_doc_strings.po
- locale/pot/pgrouting_doc_strings.pot
Porting latest changes from main
> Porting degree doc changes to develop

- doc/max_flow/flow-family.rst
Just a typo  Adcanced => Advanced
> Update flow-family.rst - fix typo (main)

- doc/max_flow/flow-family.rst
Fix typo - Adcanced => Advanced
> Update flow-family.rst fix typo

- .github/workflows/doc-check.yml
- docqueries/src/migration.result
- docqueries/src/migration.test.sql
- requirements.txt
- fix migration documentation of bdAstar
- CI: Do not use sphinx >= 7.0.0 has bugs on linkcheck
- workflow_dispatch for checking links
> Fix migration doc of bdAstar

- src/driving_distance/drivedist_driver.cpp
Fixes # .
Cleaning up C++ code
> [drivingdistance] Cleaning up C++ code

- include/c_types/restriction_t.h
- include/cpp_common/get_check_data.hpp
- src/cpp_common/get_check_data.cpp
> MacOS issues with size_t vs uint64_t

- .github/workflows/boost_version.yml
- .github/workflows/ubuntu.yml
- pgtap/mincut/stoerWagner/compare_components.pg
> Fixing issue 2602

- doc/src/support.rst
> Update mailing list to discourse

- .github/scripts/tidy-vs-commit.sh
- .github/workflows/tidy-check.yml
- Adds a CI test using clang-tidy
- works on changed src & include files 
> adding a check for clang-tidy

- include/cpp_common/pgr_base_graph.hpp
- Clean class `Pgr_base_graph`
- Remove unused code
- Code enhancement
> Cleanup pgr_base_graph 

- doc/astar/pgr_aStarCost.rst
- doc/bdAstar/pgr_bdAstarCost.rst
- doc/bdDijkstra/pgr_bdDijkstra.rst
- doc/bdDijkstra/pgr_bdDijkstraCost.rst
- doc/bellman_ford/pgr_bellmanFord.rst
- doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
- doc/coloring/pgr_edgeColoring.rst
- doc/dagShortestPath/pgr_dagShortestPath.rst
- doc/dijkstra/pgr_dijkstra.rst
- doc/dijkstra/pgr_dijkstraCost.rst
- doc/dijkstra/pgr_dijkstraVia.rst
- doc/max_flow/flow-family.rst
- doc/max_flow/pgr_maxFlow.rst
- doc/max_flow/pgr_maxFlowMinCost_Cost.rst
- doc/metrics/pgr_betweennessCentrality.rst
- doc/src/pgRouting-concepts.rst
- doc/src/pgRouting-installation.rst
- doc/trsp/pgr_trspVia.rst
- doc/trsp/pgr_trsp_withPoints.rst
- doc/withPoints/pgr_withPoints.rst
- doc/withPoints/pgr_withPointsCost.rst
Fixing errors detected by weblate
> Fixing some errors detected on weblate

- CMakeLists.txt
> Forward-port #2728 (`CMP0148` patch)

- NEWS.md
- doc/astar/pgr_aStar.rst
- doc/bdAstar/pgr_bdAstar.rst
- doc/bdDijkstra/pgr_bdDijkstra.rst
- doc/bellman_ford/pgr_bellmanFord.rst
- doc/circuits/pgr_hawickCircuits.rst
- doc/components/pgr_bridges.rst
- doc/dominator/pgr_lengauerTarjanDominatorTree.rst
- doc/driving_distance/pgr_drivingDistance.rst
- doc/lineGraph/pgr_lineGraphFull.rst
- doc/max_flow/pgr_edmondsKarp.rst
- doc/metrics/pgr_betweennessCentrality.rst
- doc/src/migration.rst
- doc/src/release_notes.rst
- doc/utilities/pgr_findCloseEdges.rst
- doc/withPoints/pgr_withPointsCost.rst
- locale/en/LC_MESSAGES/pgrouting_doc_strings.po
- locale/pot/pgrouting_doc_strings.pot
Standardizing some small phrases & bug fixes on documentation
> (doc) Standardizing some small phrases & bug fixes

- NEWS.md
- doc/astar/pgr_aStar.rst
- doc/bdAstar/bdAstar-family.rst
- doc/src/release_notes.rst
- locale/en/LC_MESSAGES/pgrouting_doc_strings.po
- locale/pot/pgrouting_doc_strings.pot
- Standardizing pgr_aStar name
> Standardizing pgr_aStar name

- NEWS.md
- doc/metrics/pgr_degree.rst
- doc/src/migration.rst
- doc/src/pgRouting-concepts.rst
- doc/src/release_notes.rst
- doc/topology/pgr_analyzeGraph.rst
- docqueries/src/migration.pg
- docqueries/src/migration.result
- docqueries/topology/analyzeGraph.result
- docqueries/topology/nodeNetwork.result
- locale/en/LC_MESSAGES/pgrouting_doc_strings.po
- locale/pot/pgrouting_doc_strings.pot
- sql/topology/analyzegraph.sql
> Port deprecation of pgr analyze graph

- NEWS.md
- doc/_static/page_history.js
- doc/alpha_shape/pgr_alphaShape.rst
- doc/driving_distance/pgr_drivingDistance.rst
- doc/src/migration.rst
- doc/src/release_notes.rst
- doc/withPoints/pgr_withPointsDD.rst
- docqueries/alpha_shape/alphashape.result
- locale/en/LC_MESSAGES/pgrouting_doc_strings.po
- locale/pot/pgrouting_doc_strings.pot
- sql/alpha_shape/alphaShape.sql
> Deprecating pgr AlphaShape

- tools/developer/run.sh
Adding lines/instructions in run.sh for developing with macOS Homebrew
- some small indication for macOS HOmebrew 
> (tools) A…dding lines/instructions in run.sh for developing with macOS

- doc/allpairs/pgr_johnson.rst
> (doc/pgr_jhonson) Fix name

- .github/workflows/update.yml
- pgtap/ordering/topologicalSort/edge_cases.pg
- pgtap/withPoints/withPoints/types_check.pg
- pgtap/withPoints/withPointsDD/edge_cases/allowed_driving_side.pg
- Some tests are not valid for old version
- Forcing the update test to run 
- those pgtap tests were failing because it was not forced
> Fix updatetest

- ci/winnie/build_pgrouting.sh
> Don't assume no GCC_TYPE means 81, as new will be unmarked

- include/drivers/ordering_driver.hpp
> Add missing include for int64_t
